/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.TheatreAdminRole;

import Project.SmartCity.Establishment.Shop;
import Project.SmartCity.Establishment.Theatre;
import Project.SmartCity.SmartCity;
import Project.UserAccount.UserAccount;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Okami
 */
public class TheatreAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TheatreAdminWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private SmartCity business;

    Theatre theatre;
    public TheatreAdminWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, SmartCity business) {
        initComponents();
        this.business = business;
        this.userAccount = account;
        this.userProcessContainer = userProcessContainer;
        for(Theatre t:business.getTheatreDirectory().getTheatreList()){
            if(t.getUsername().equals(userAccount.getUsername())){
                theatre = t;
                break;
            }
        }
        movienametxt.setEnabled(false);
        moviecosttxt.setEnabled(false);
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ordertbl = new javax.swing.JScrollPane();
        theatrecontentstbl = new javax.swing.JTable();
        plusbtn = new javax.swing.JButton();
        minusbtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        movienametxt = new javax.swing.JTextField();
        moviecosttxt = new javax.swing.JTextField();
        addbtn = new javax.swing.JButton();
        confirmupdatebtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(251, 211, 245));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LIST OF MOVIES IN THEATRE");

        theatrecontentstbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Movie", "Cost"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ordertbl.setViewportView(theatrecontentstbl);

        plusbtn.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        plusbtn.setForeground(new java.awt.Color(0, 51, 51));
        plusbtn.setText("Add Item");
        plusbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusbtnActionPerformed(evt);
            }
        });

        minusbtn.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        minusbtn.setForeground(new java.awt.Color(0, 51, 51));
        minusbtn.setText("Remove Item");
        minusbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusbtnActionPerformed(evt);
            }
        });

        updatebtn.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        updatebtn.setForeground(new java.awt.Color(0, 51, 51));
        updatebtn.setText("Update Item");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        movienametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movienametxtActionPerformed(evt);
            }
        });

        moviecosttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moviecosttxtActionPerformed(evt);
            }
        });

        addbtn.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        addbtn.setForeground(new java.awt.Color(0, 51, 51));
        addbtn.setText("Add to List");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        confirmupdatebtn.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        confirmupdatebtn.setForeground(new java.awt.Color(0, 51, 51));
        confirmupdatebtn.setText("Confirm Update");
        confirmupdatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmupdatebtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("Movie:");

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("Cost:");

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(25, 56, 82));
        jLabel6.setText("THEATRE ADMIN PANEL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(ordertbl, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(4, 4, 4))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(plusbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(47, 47, 47)
                            .addComponent(minusbtn)
                            .addGap(43, 43, 43)
                            .addComponent(updatebtn))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(addbtn)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(movienametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(47, 47, 47)
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(moviecosttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(37, 37, 37)
                                    .addComponent(confirmupdatebtn))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(95, 95, 95))))
                .addContainerGap(391, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel6)
                .addGap(66, 66, 66)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(ordertbl, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plusbtn)
                    .addComponent(minusbtn)
                    .addComponent(updatebtn))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(movienametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(moviecosttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addbtn)
                    .addComponent(confirmupdatebtn))
                .addContainerGap(70, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void plusbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusbtnActionPerformed
        // TODO add your handling code here:
        movienametxt.setEnabled(true);
        moviecosttxt.setEnabled(true);
        addbtn.setEnabled(true);
    }//GEN-LAST:event_plusbtnActionPerformed

    private void minusbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusbtnActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = theatrecontentstbl.getSelectedRow();

        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a row to be deleted.");
            return;
        }

        DefaultTableModel records = (DefaultTableModel) theatrecontentstbl.getModel();
        String name = (String) records.getValueAt(selectedRowIndex, 0);
        theatre.getMovies().remove(name);
        populateTable();
        //menu.removeItem();
    }//GEN-LAST:event_minusbtnActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        // TODO add your handling code here:
        movienametxt.setEnabled(true);
        moviecosttxt.setEnabled(true);
        confirmupdatebtn.setEnabled(true);
        int selectedRowIndex = theatrecontentstbl.getSelectedRow();

        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a row to be updated.");
            return;
        }
        DefaultTableModel records = (DefaultTableModel) theatrecontentstbl.getModel();
        String name = (String) records.getValueAt(selectedRowIndex, 0);
        movienametxt.setText(name);
        moviecosttxt.setText(Integer.toString(theatre.getMovies().get(name)));
    }//GEN-LAST:event_updatebtnActionPerformed

    private void movienametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movienametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_movienametxtActionPerformed

    private void moviecosttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moviecosttxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moviecosttxtActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        // TODO add your handling code here:
        try{

            HashMap<String, Integer> movies = theatre.getMovies();
            movies.put(movienametxt.getText(), Integer.parseInt(moviecosttxt.getText()));
            theatre.setMovies(movies);
            populateTable();
            moviecosttxt.setText("");
            movienametxt.setText("");
            moviecosttxt.setEnabled(false);
            movienametxt.setEnabled(false);
            addbtn.setEnabled(false);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
        populateTable();
    }//GEN-LAST:event_addbtnActionPerformed

    private void confirmupdatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmupdatebtnActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = theatrecontentstbl.getSelectedRow();

        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a row to be updated.");
            return;
        }

        DefaultTableModel records = (DefaultTableModel) theatrecontentstbl.getModel();
        String name = (String) records.getValueAt(selectedRowIndex, 0);
        theatre.getMovies().remove(name);
        theatre.getMovies().put(movienametxt.getText(), Integer.parseInt(moviecosttxt.getText()));
        moviecosttxt.setText("");
        movienametxt.setText("");
        moviecosttxt.setEnabled(false);
        movienametxt.setEnabled(false);
        confirmupdatebtn.setEnabled(false);
        populateTable();
    }//GEN-LAST:event_confirmupdatebtnActionPerformed

    private void populateTable() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    //Shop restaurant = business.getRestaurantDirectory().getRestaurantList().get(0);
        
        DefaultTableModel records = (DefaultTableModel) theatrecontentstbl.getModel();
        records.setRowCount(0); //Clear empty records
        
        for(String s : theatre.getMovies().keySet()){
            Object[] row = new Object[2];
            row[0] = s;
            //row[0] = vs.getDate();
            row[1] = theatre.getMovies().get(s);
            
            records.addRow(row);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JButton confirmupdatebtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton minusbtn;
    private javax.swing.JTextField moviecosttxt;
    private javax.swing.JTextField movienametxt;
    private javax.swing.JScrollPane ordertbl;
    private javax.swing.JButton plusbtn;
    private javax.swing.JTable theatrecontentstbl;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables
}
