/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.GeneralUserRole;

import Project.SmartCity.SmartCity;
import Project.UserAccount.UserAccount;
import javax.swing.JPanel;

/**
 *
 * @author harooniqbal
 */
public class GeneralUserRoleWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form GeneralUserRoleWorkAreaJPanel
     */
    private JPanel userProcessContainer;

    private UserAccount userAccount;
    
    private SmartCity business;
    

    public GeneralUserRoleWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, SmartCity business) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    initComponents();
        this.business = business;
        this.userAccount = account;
        this.userProcessContainer = userProcessContainer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabelgeneraluser = new javax.swing.JLabel();
        jButtonhealth = new javax.swing.JButton();
        jLabelpanel = new javax.swing.JLabel();
        jButtoneducation = new javax.swing.JButton();
        jButtonestablishments = new javax.swing.JButton();
        jButtontransport = new javax.swing.JButton();
        jButtontourism = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        jSplitPane1.setDividerLocation(180);
        jSplitPane1.setDividerSize(0);

        jPanel1.setBackground(new java.awt.Color(255, 181, 176));
        jPanel1.setForeground(new java.awt.Color(0, 51, 51));

        jLabelgeneraluser.setBackground(new java.awt.Color(255, 204, 204));
        jLabelgeneraluser.setForeground(new java.awt.Color(0, 51, 51));
        jLabelgeneraluser.setText("GENERAL USER ");

        jButtonhealth.setBackground(new java.awt.Color(255, 255, 255));
        jButtonhealth.setForeground(new java.awt.Color(0, 51, 51));
        jButtonhealth.setText("Healthcare Module");

        jLabelpanel.setBackground(new java.awt.Color(255, 204, 204));
        jLabelpanel.setForeground(new java.awt.Color(0, 51, 51));
        jLabelpanel.setText("PANEL");

        jButtoneducation.setBackground(new java.awt.Color(255, 255, 255));
        jButtoneducation.setForeground(new java.awt.Color(0, 51, 51));
        jButtoneducation.setText("Education Module");

        jButtonestablishments.setBackground(new java.awt.Color(255, 255, 255));
        jButtonestablishments.setForeground(new java.awt.Color(0, 51, 51));
        jButtonestablishments.setText("Establishment Module");

        jButtontransport.setBackground(new java.awt.Color(255, 255, 255));
        jButtontransport.setForeground(new java.awt.Color(0, 51, 51));
        jButtontransport.setText("Transportation Module");

        jButtontourism.setBackground(new java.awt.Color(255, 255, 255));
        jButtontourism.setForeground(new java.awt.Color(0, 51, 51));
        jButtontourism.setText("Tourism Module");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonestablishments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtoneducation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonhealth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtontransport, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jButtontourism, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabelgeneraluser))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabelpanel)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jLabelgeneraluser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelpanel)
                .addGap(78, 78, 78)
                .addComponent(jButtonhealth)
                .addGap(32, 32, 32)
                .addComponent(jButtoneducation)
                .addGap(33, 33, 33)
                .addComponent(jButtonestablishments)
                .addGap(31, 31, 31)
                .addComponent(jButtontransport)
                .addGap(36, 36, 36)
                .addComponent(jButtontourism)
                .addContainerGap(259, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setForeground(new java.awt.Color(0, 51, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 778, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 732, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtoneducation;
    private javax.swing.JButton jButtonestablishments;
    private javax.swing.JButton jButtonhealth;
    private javax.swing.JButton jButtontourism;
    private javax.swing.JButton jButtontransport;
    private javax.swing.JLabel jLabelgeneraluser;
    private javax.swing.JLabel jLabelpanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
