/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.GeneralUserRole;

/**
 *
 * @author harooniqbal
 */
public class GeneralUserEstablishmentModulePanel extends javax.swing.JPanel {

    /**
     * Creates new form GeneralUserEstablishmentModulePanel
     */
    public GeneralUserEstablishmentModulePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonshop = new javax.swing.JButton();
        jButtonrest = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabletouristplace = new javax.swing.JTable();
        jButtonshowlocation = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));
        setForeground(new java.awt.Color(0, 51, 51));

        jButtonshop.setBackground(new java.awt.Color(255, 255, 255));
        jButtonshop.setForeground(new java.awt.Color(0, 51, 51));
        jButtonshop.setText("View Shops");

        jButtonrest.setBackground(new java.awt.Color(255, 255, 255));
        jButtonrest.setForeground(new java.awt.Color(0, 51, 51));
        jButtonrest.setText("View Restaurants");

        jTabletouristplace.setBackground(new java.awt.Color(255, 255, 255));
        jTabletouristplace.setForeground(new java.awt.Color(0, 51, 51));
        jTabletouristplace.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Location"
            }
        ));
        jScrollPane1.setViewportView(jTabletouristplace);

        jButtonshowlocation.setBackground(new java.awt.Color(255, 255, 255));
        jButtonshowlocation.setForeground(new java.awt.Color(0, 51, 51));
        jButtonshowlocation.setText("Show Location");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jButtonshop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonrest)
                .addGap(214, 214, 214))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(416, 416, 416)
                        .addComponent(jButtonshowlocation)))
                .addContainerGap(262, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonshop)
                    .addComponent(jButtonrest))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButtonshowlocation)
                .addContainerGap(131, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonrest;
    private javax.swing.JButton jButtonshop;
    private javax.swing.JButton jButtonshowlocation;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabletouristplace;
    // End of variables declaration//GEN-END:variables
}
