/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.GeneralUserRole;

/**
 *
 * @author harooniqbal
 */
public class GeneralUserTransportationModulePanel extends javax.swing.JPanel {

    /**
     * Creates new form GeneralUserTransportationModulePanel
     */
    public GeneralUserTransportationModulePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonbus = new javax.swing.JButton();
        jButtontrain = new javax.swing.JButton();
        jButtonflight = new javax.swing.JButton();
        jButtoncruise = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablevehicle = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 204, 204));
        setForeground(new java.awt.Color(0, 51, 51));

        jButtonbus.setBackground(new java.awt.Color(255, 255, 255));
        jButtonbus.setForeground(new java.awt.Color(0, 51, 51));
        jButtonbus.setText("View Buses");

        jButtontrain.setBackground(new java.awt.Color(255, 255, 255));
        jButtontrain.setForeground(new java.awt.Color(0, 51, 51));
        jButtontrain.setText("View Trains");

        jButtonflight.setBackground(new java.awt.Color(255, 255, 255));
        jButtonflight.setForeground(new java.awt.Color(0, 51, 51));
        jButtonflight.setText("View Flights");

        jButtoncruise.setBackground(new java.awt.Color(255, 255, 255));
        jButtoncruise.setForeground(new java.awt.Color(0, 51, 51));
        jButtoncruise.setText("View Cruises");

        jTablevehicle.setBackground(new java.awt.Color(255, 255, 255));
        jTablevehicle.setForeground(new java.awt.Color(0, 51, 51));
        jTablevehicle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Vehicle Number", "Start Location", "Drop Location"
            }
        ));
        jScrollPane1.setViewportView(jTablevehicle);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonbus)
                        .addGap(67, 67, 67)
                        .addComponent(jButtontrain)
                        .addGap(61, 61, 61)
                        .addComponent(jButtonflight)
                        .addGap(64, 64, 64)
                        .addComponent(jButtoncruise)))
                .addGap(231, 231, 231))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtoncruise)
                    .addComponent(jButtonflight)
                    .addComponent(jButtontrain)
                    .addComponent(jButtonbus))
                .addGap(90, 90, 90)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonbus;
    private javax.swing.JButton jButtoncruise;
    private javax.swing.JButton jButtonflight;
    private javax.swing.JButton jButtontrain;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablevehicle;
    // End of variables declaration//GEN-END:variables
}
