/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.GeneralUserRole;

/**
 *
 * @author harooniqbal
 */
public class GeneralUserEducationModulePanel extends javax.swing.JPanel {

    /**
     * Creates new form GeneralUserEducationModulePanel
     */
    public GeneralUserEducationModulePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonviewschool = new javax.swing.JButton();
        jButtonviewuniv = new javax.swing.JButton();
        jButtonshowlocation = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableschool = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablefaculty = new javax.swing.JTable();
        jButtongoto4 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTablefacultyachieve1 = new javax.swing.JTable();
        jButtongoto5 = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTablefacultypublish1 = new javax.swing.JTable();
        jButtongoto3 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTablefacultycourses1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 204, 204));
        setForeground(new java.awt.Color(0, 51, 51));

        jButtonviewschool.setBackground(new java.awt.Color(255, 255, 255));
        jButtonviewschool.setForeground(new java.awt.Color(0, 51, 51));
        jButtonviewschool.setText("View Schools");

        jButtonviewuniv.setBackground(new java.awt.Color(255, 255, 255));
        jButtonviewuniv.setForeground(new java.awt.Color(0, 51, 51));
        jButtonviewuniv.setText("View Universities");

        jButtonshowlocation.setBackground(new java.awt.Color(255, 255, 255));
        jButtonshowlocation.setForeground(new java.awt.Color(0, 51, 51));
        jButtonshowlocation.setText("Show Location");

        jTableschool.setBackground(new java.awt.Color(255, 255, 255));
        jTableschool.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Location"
            }
        ));
        jScrollPane1.setViewportView(jTableschool);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(0, 51, 51));
        jButton1.setText(">>");

        jTablefaculty.setBackground(new java.awt.Color(255, 255, 255));
        jTablefaculty.setForeground(new java.awt.Color(0, 51, 51));
        jTablefaculty.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Faculty", "Experience", "Interest Areas"
            }
        ));
        jScrollPane2.setViewportView(jTablefaculty);

        jButtongoto4.setBackground(new java.awt.Color(255, 255, 255));
        jButtongoto4.setForeground(new java.awt.Color(0, 51, 51));
        jButtongoto4.setText("Go to");

        jScrollPane7.setBackground(new java.awt.Color(255, 181, 176));

        jTablefacultyachieve1.setBackground(new java.awt.Color(255, 255, 255));
        jTablefacultyachieve1.setForeground(new java.awt.Color(0, 51, 51));
        jTablefacultyachieve1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Achievements"
            }
        ));
        jScrollPane7.setViewportView(jTablefacultyachieve1);

        jButtongoto5.setBackground(new java.awt.Color(255, 255, 255));
        jButtongoto5.setForeground(new java.awt.Color(0, 51, 51));
        jButtongoto5.setText("Go to");

        jScrollPane8.setBackground(new java.awt.Color(255, 181, 176));
        jScrollPane8.setForeground(new java.awt.Color(0, 51, 51));

        jTablefacultypublish1.setBackground(new java.awt.Color(255, 255, 255));
        jTablefacultypublish1.setForeground(new java.awt.Color(0, 51, 51));
        jTablefacultypublish1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Publications"
            }
        ));
        jScrollPane8.setViewportView(jTablefacultypublish1);

        jButtongoto3.setBackground(new java.awt.Color(255, 255, 255));
        jButtongoto3.setForeground(new java.awt.Color(0, 51, 51));
        jButtongoto3.setText("Go to");

        jScrollPane6.setBackground(new java.awt.Color(255, 181, 176));

        jTablefacultycourses1.setBackground(new java.awt.Color(255, 255, 255));
        jTablefacultycourses1.setForeground(new java.awt.Color(0, 51, 51));
        jTablefacultycourses1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Courses"
            }
        ));
        jScrollPane6.setViewportView(jTablefacultycourses1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(278, Short.MAX_VALUE)
                .addComponent(jButtonviewschool)
                .addGap(173, 173, 173)
                .addComponent(jButtonviewuniv)
                .addGap(296, 296, 296))
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jButtonshowlocation)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(62, 62, 62)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jButton1)
                                .addGap(35, 35, 35)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(103, 103, 103)
                            .addComponent(jButtongoto4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtongoto5)
                            .addGap(235, 235, 235)
                            .addComponent(jButtongoto3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(103, 103, 103)))
                    .addGap(63, 63, 63)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonviewuniv)
                    .addComponent(jButtonviewschool))
                .addGap(272, 272, 272)
                .addComponent(jButtonshowlocation)
                .addContainerGap(370, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(193, 193, 193)
                                .addComponent(jButton1)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(73, 73, 73)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(97, 97, 97)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtongoto3)
                        .addComponent(jButtongoto5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtongoto4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(29, 29, 29)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(73, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtongoto3;
    private javax.swing.JButton jButtongoto4;
    private javax.swing.JButton jButtongoto5;
    private javax.swing.JButton jButtonshowlocation;
    private javax.swing.JButton jButtonviewschool;
    private javax.swing.JButton jButtonviewuniv;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTable jTablefaculty;
    private javax.swing.JTable jTablefacultyachieve1;
    private javax.swing.JTable jTablefacultycourses1;
    private javax.swing.JTable jTablefacultypublish1;
    private javax.swing.JTable jTableschool;
    // End of variables declaration//GEN-END:variables
}
