/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.ShopAdminRole;

import Project.SmartCity.SmartCity;
import Project.UserAccount.UserAccount;
import javax.swing.JPanel;

/**
 *
 * @author harooniqbal
 */
public class ShopAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ShopAdminWorkAreaJPanel
     */
     private JPanel userProcessContainer;

    private UserAccount userAccount;
    
    private SmartCity business;
    public ShopAdminWorkAreaJPanel() {
        
    }

    public ShopAdminWorkAreaJPanel(JPanel userProcessContainer, SmartCity business, UserAccount account) {
        initComponents();
        this.business = business;
        this.userAccount = account;
        this.userProcessContainer = userProcessContainer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabelrestadminpanel = new javax.swing.JLabel();
        jLabelpanel = new javax.swing.JLabel();
        jButtonmanageorder = new javax.swing.JButton();
        jButtonmanageitems = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jSplitPane1.setDividerLocation(160);
        jSplitPane1.setDividerSize(0);

        jPanel1.setBackground(new java.awt.Color(180, 180, 231));
        jPanel1.setForeground(new java.awt.Color(0, 51, 51));

        jLabelrestadminpanel.setBackground(new java.awt.Color(212, 217, 235));
        jLabelrestadminpanel.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabelrestadminpanel.setForeground(new java.awt.Color(0, 51, 51));
        jLabelrestadminpanel.setText("SHOP ADMIN");

        jLabelpanel.setBackground(new java.awt.Color(212, 217, 235));
        jLabelpanel.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabelpanel.setForeground(new java.awt.Color(0, 51, 51));
        jLabelpanel.setText("PANEL");

        jButtonmanageorder.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jButtonmanageorder.setForeground(new java.awt.Color(0, 51, 51));
        jButtonmanageorder.setText("Manage Orders");
        jButtonmanageorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonmanageorderActionPerformed(evt);
            }
        });

        jButtonmanageitems.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jButtonmanageitems.setForeground(new java.awt.Color(0, 51, 51));
        jButtonmanageitems.setText("Manage Items");
        jButtonmanageitems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonmanageitemsActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon("/Users/harooniqbal/Desktop/AEDProjectImages/shopadminicon.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(70, 70, 70)
                            .addComponent(jLabelpanel))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButtonmanageitems)
                                .addComponent(jButtonmanageorder)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabelrestadminpanel)
                            .addGap(20, 20, 20)))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jLabelrestadminpanel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelpanel)
                .addGap(79, 79, 79)
                .addComponent(jButtonmanageorder)
                .addGap(35, 35, 35)
                .addComponent(jButtonmanageitems)
                .addContainerGap(330, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(212, 217, 235));
        jPanel2.setForeground(new java.awt.Color(0, 51, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/harooniqbal/Desktop/AEDProjectImages/shopbg.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(jLabel1)
                .addContainerGap(305, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(297, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonmanageorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonmanageorderActionPerformed
        // TODO add your handling code here:
         ShopAdminManageOrdersPanel menu = new ShopAdminManageOrdersPanel(userProcessContainer, userAccount,business);
            jSplitPane1.setRightComponent(menu);
//        }
    }//GEN-LAST:event_jButtonmanageorderActionPerformed

    private void jButtonmanageitemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonmanageitemsActionPerformed
        // TODO add your handling code here:
        ShopAdminManageItemsPanel menu = new ShopAdminManageItemsPanel(userProcessContainer, userAccount,business);
            jSplitPane1.setRightComponent(menu);
    }//GEN-LAST:event_jButtonmanageitemsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonmanageitems;
    private javax.swing.JButton jButtonmanageorder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabelpanel;
    private javax.swing.JLabel jLabelrestadminpanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
