/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.PatientRole;

import Project.SmartCity.HealthcareRoles.Patient;
import Project.SmartCity.HealthcareRoles.Pharmacist;
import Project.SmartCity.HealthcareSystem.Pharmacy;
import Project.SmartCity.HealthcareSystem.Prescription;
import Project.SmartCity.SmartCity;
import Project.UserAccount.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author harooniqbal
 */
public class PatientGetPrescriptionPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientGetPrescriptionPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private SmartCity business;
    Patient patient;
    
    public PatientGetPrescriptionPanel(JPanel userProcessContainer, UserAccount account, SmartCity business) {
        initComponents();
        this.business = business;
        this.userAccount = account;
        this.userProcessContainer = userProcessContainer;
        for (Patient c : business.getPatientDirectory().getPatientList()){
            if(c.getUsername().equals(userAccount.getUsername())){
                patient = c;
                break;
            }
        }
        populateTable();
        populateTable2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTablepresctable = new javax.swing.JTable();
        jLabelselecthosp = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablepharmname = new javax.swing.JTable();
        jButtongoto2 = new javax.swing.JButton();
        jLabelselectdoc = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTablepharmacist = new javax.swing.JTable();
        jButtoncreateprescreq = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelselecthosp1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 238, 204));
        setForeground(new java.awt.Color(0, 51, 51));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setForeground(new java.awt.Color(0, 51, 51));

        jTablepresctable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Prescription ID", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTablepresctable);

        jLabelselecthosp.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabelselecthosp.setForeground(new java.awt.Color(0, 51, 51));
        jLabelselecthosp.setText("Select Pharmacy:");

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setForeground(new java.awt.Color(0, 51, 51));

        jTablepharmname.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Pharmacy Name"
            }
        ));
        jScrollPane2.setViewportView(jTablepharmname);

        jButtongoto2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jButtongoto2.setForeground(new java.awt.Color(0, 51, 51));
        jButtongoto2.setText(">>");
        jButtongoto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtongoto2ActionPerformed(evt);
            }
        });

        jLabelselectdoc.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabelselectdoc.setForeground(new java.awt.Color(0, 51, 51));
        jLabelselectdoc.setText("Select Pharmacist:");

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setForeground(new java.awt.Color(0, 51, 51));

        jTablepharmacist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Pharmacist Name"
            }
        ));
        jScrollPane3.setViewportView(jTablepharmacist);

        jButtoncreateprescreq.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jButtoncreateprescreq.setForeground(new java.awt.Color(0, 51, 51));
        jButtoncreateprescreq.setText("Create Prescription Request");
        jButtoncreateprescreq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncreateprescreqActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon("/Users/harooniqbal/Desktop/AEDProjectImages/patientlogo.png")); // NOI18N

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(25, 56, 82));
        jLabel6.setText("PATIENT GET PRESCRIPTION");

        jLabelselecthosp1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabelselecthosp1.setForeground(new java.awt.Color(0, 51, 51));
        jLabelselecthosp1.setText("Select Prescription:");

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/harooniqbal/Desktop/AEDProjectImages/prescbg.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(190, 190, 190)
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelselecthosp1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtoncreateprescreq)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtongoto2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelselecthosp, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelselectdoc, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(103, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel6)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelselecthosp)
                            .addComponent(jLabelselectdoc)
                            .addComponent(jLabelselecthosp1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jButtongoto2)))
                .addGap(96, 96, 96)
                .addComponent(jButtoncreateprescreq)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtongoto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtongoto2ActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex1 = jTablepresctable.getSelectedRow();
        
        if(selectedRowIndex1 < 0){
            JOptionPane.showMessageDialog(this, "Please select a prescription.");
            return;
        }
        
        int selectedRowIndex = jTablepharmname.getSelectedRow();
        
        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a pharmacy.");
            return;
        }
        
        DefaultTableModel records = (DefaultTableModel) jTablepharmname.getModel();
        String name = (String) records.getValueAt(selectedRowIndex, 0);
       
        populateTable3(business.getPharmacyDirectory().getPharmacy(name));
    }//GEN-LAST:event_jButtongoto2ActionPerformed

    private void jButtoncreateprescreqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncreateprescreqActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = jTablepresctable.getSelectedRow();
        
        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a prescription.");
            return;
        }
        
        DefaultTableModel records = (DefaultTableModel) jTablepresctable.getModel();
        Integer id = (Integer) records.getValueAt(selectedRowIndex, 0);
        
        Prescription precription = patient.getPresdirectory().getPrescription(id);
        
        selectedRowIndex = jTablepharmname.getSelectedRow();
        
        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a pharmacy.");
            return;
        }
        
        records = (DefaultTableModel) jTablepharmname.getModel();
        String name = (String) records.getValueAt(selectedRowIndex, 0);
        
        Pharmacy pharmacy = business.getPharmacyDirectory().getPharmacy(name);
        
        selectedRowIndex = jTablepharmacist.getSelectedRow();
        
        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a pharmacy.");
            return;
        }
        
        records = (DefaultTableModel) jTablepharmacist.getModel();
        id = (Integer) records.getValueAt(selectedRowIndex, 0);
        
        Pharmacist pharmacist = pharmacy.getPharmacistDirectory().getPharmacist(id);
        
        precription.setStatus("Active");
        
        pharmacist.getPresdirectory().getPrescriptionList().add(precription);
        pharmacy.getPrescriptionDirectory().getPrescriptionList().add(precription);
        
        pharmacy.getPatientDirectory().getPatientList().add(patient);
        JOptionPane.showMessageDialog(this, "Prescription Request Created");
    }//GEN-LAST:event_jButtoncreateprescreqActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtoncreateprescreq;
    private javax.swing.JButton jButtongoto2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelselectdoc;
    private javax.swing.JLabel jLabelselecthosp;
    private javax.swing.JLabel jLabelselecthosp1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTablepharmacist;
    private javax.swing.JTable jTablepharmname;
    private javax.swing.JTable jTablepresctable;
    // End of variables declaration//GEN-END:variables
private void populateTable() {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        DefaultTableModel records = (DefaultTableModel) jTablepresctable.getModel();
        records.setRowCount(0); //Clear empty records
        for(Prescription o : patient.getPresdirectory().getPrescriptionList()){
                if(o.getStatus().equals("Active")){
                Object[] row = new Object[2];
                row[0] = o.getId();
                row[1] = o.getStatus();

                records.addRow(row);
            }
        }
    }

    private void populateTable2() {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        DefaultTableModel records = (DefaultTableModel) jTablepharmname.getModel();
        records.setRowCount(0); //Clear empty records
        for(Pharmacy p : business.getPharmacyDirectory().getPharmacyList()){
            Object[] row = new Object[1];
            row[0] = p.getName();
            
            records.addRow(row);
        }
    }

    private void populateTable3(Pharmacy pharmacy) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        DefaultTableModel records = (DefaultTableModel) jTablepharmacist.getModel();
        records.setRowCount(0); //Clear empty records
        for(Pharmacist p : pharmacy.getPharmacistDirectory().getPharmacistList()){
            Object[] row = new Object[2];
            row[0] = p.getPharmacistid();
            row[1] = p.getName();
            
            records.addRow(row);
        }
    }


}
