/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.PatientRole;

import Project.SmartCity.HealthcareRoles.Doctor;
import Project.SmartCity.HealthcareRoles.Patient;
import Project.SmartCity.HealthcareSystem.Appointment;
import Project.SmartCity.HealthcareSystem.Hospital;
import Project.SmartCity.SmartCity;
import Project.UserAccount.UserAccount;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author harooniqbal
 */
public class PatientBookAppointmentPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientBookAppointmentPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private SmartCity business;
    
    Patient patient;
    public PatientBookAppointmentPanel(JPanel userProcessContainer, UserAccount account, SmartCity business) {
        initComponents();
        this.business = business;
        this.userAccount = account;
        this.userProcessContainer = userProcessContainer;
        
        for (Patient c : business.getPatientDirectory().getPatientList()){
            if(c.getUsername().equals(userAccount.getUsername())){
                patient = c;
                break;
            }
        }
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jLabelappdate = new javax.swing.JLabel();
        jLabelselecthosp = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablehospname = new javax.swing.JTable();
        jButtongoto = new javax.swing.JButton();
        jLabelselectdoc = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablehospname1 = new javax.swing.JTable();
        jLabelsymptoms = new javax.swing.JLabel();
        jTextFieldsymptoms = new javax.swing.JTextField();
        jButtongoto1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        jMenu1.setText("jMenu1");

        setBackground(new java.awt.Color(204, 238, 204));
        setForeground(new java.awt.Color(0, 51, 51));

        jLabelappdate.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabelappdate.setForeground(new java.awt.Color(0, 51, 51));
        jLabelappdate.setText("Select Appointment Date:");

        jLabelselecthosp.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabelselecthosp.setForeground(new java.awt.Color(0, 51, 51));
        jLabelselecthosp.setText("Select Hospital:");

        jScrollPane1.setForeground(new java.awt.Color(0, 51, 51));

        jTablehospname.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Hospital Name"
            }
        ));
        jScrollPane1.setViewportView(jTablehospname);

        jButtongoto.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jButtongoto.setForeground(new java.awt.Color(0, 51, 51));
        jButtongoto.setText(">>");
        jButtongoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtongotoActionPerformed(evt);
            }
        });

        jLabelselectdoc.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabelselectdoc.setForeground(new java.awt.Color(0, 51, 51));
        jLabelselectdoc.setText("Select Doctor:");

        jScrollPane2.setForeground(new java.awt.Color(0, 51, 51));

        jTablehospname1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Doctor Name", "Specialty"
            }
        ));
        jScrollPane2.setViewportView(jTablehospname1);

        jLabelsymptoms.setBackground(new java.awt.Color(0, 51, 51));
        jLabelsymptoms.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabelsymptoms.setForeground(new java.awt.Color(0, 51, 51));
        jLabelsymptoms.setText("Symptoms:");

        jTextFieldsymptoms.setForeground(new java.awt.Color(0, 51, 51));

        jButtongoto1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jButtongoto1.setForeground(new java.awt.Color(0, 51, 51));
        jButtongoto1.setText("Book Appointment");
        jButtongoto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtongoto1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(25, 56, 82));
        jLabel6.setText("PATIENT BOOK APPOINTMENT");

        jLabel11.setIcon(new javax.swing.ImageIcon("/Users/harooniqbal/Desktop/AEDProjectImages/patientlogo.png")); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/harooniqbal/Desktop/AEDProjectImages/appointmentbg.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(195, 195, 195)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(jButtongoto, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelselecthosp, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelappdate, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(151, 151, 151)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelselectdoc, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelsymptoms, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(jTextFieldsymptoms, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(323, 323, 323)
                .addComponent(jButtongoto1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 228, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel6))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabelappdate))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelselectdoc, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelselecthosp))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jButtongoto))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelsymptoms)
                    .addComponent(jTextFieldsymptoms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jButtongoto1)
                        .addContainerGap(197, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtongotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtongotoActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = jTablehospname.getSelectedRow();
        
        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a Hospital.");
            return;
        }
        
        DefaultTableModel records = (DefaultTableModel) jTablehospname.getModel();
        String name = (String) records.getValueAt(selectedRowIndex, 0);
        
        Hospital hospital  = business.getHospitalDirectory().getHospital(name);
        
        DefaultTableModel records1 = (DefaultTableModel) jTablehospname1.getModel();
        records1.setRowCount(0); //Clear empty records
        for(Doctor o : hospital.getDoctorDirectory().getDoctorList()){
            Object[] row = new Object[2];
            row[0] = o.getName();
            row[1] = o.getSpecialty();
                    
            records1.addRow(row);
        }
    }//GEN-LAST:event_jButtongotoActionPerformed

    private void jButtongoto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtongoto1ActionPerformed
        // TODO add your handling code here:
        Date d = jDateChooser1.getDate();  
        DateFormat dateFormat = new SimpleDateFormat("MMM d, yyyy");  
        String date = dateFormat.format(d); 
        
        int selectedRowIndex = jTablehospname.getSelectedRow();
        
        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a hospital.");
            return;
        }
        
        DefaultTableModel records = (DefaultTableModel) jTablehospname.getModel();
        String name = (String) records.getValueAt(selectedRowIndex, 0);
        
        Hospital hospital  = business.getHospitalDirectory().getHospital(name);
        
        selectedRowIndex = jTablehospname.getSelectedRow();
        
        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a doctor.");
            return;
        }
        
        DefaultTableModel records1 = (DefaultTableModel) jTablehospname1.getModel();
        name = (String) records1.getValueAt(selectedRowIndex, 0);
        
        Doctor doctor  = hospital.getDoctorDirectory().getDoctor(name);
        
        
        String symptoms[] = jTextFieldsymptoms.getText().split(",",-2);
        
        Appointment a = patient.getApplist().createAppointment(date, symptoms);
        doctor.getApplist().getAppointmentList().add(a);
        hospital.getAppointmentDirectory().getAppointmentList().add(a);
        
        hospital.getPatientDirectory().getPatientList().add(patient);
        jTextFieldsymptoms.setText("");
        JOptionPane.showMessageDialog(this, "Appointment Booked");
    
    }//GEN-LAST:event_jButtongoto1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtongoto;
    private javax.swing.JButton jButtongoto1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelappdate;
    private javax.swing.JLabel jLabelselectdoc;
    private javax.swing.JLabel jLabelselecthosp;
    private javax.swing.JLabel jLabelsymptoms;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTablehospname;
    private javax.swing.JTable jTablehospname1;
    private javax.swing.JTextField jTextFieldsymptoms;
    // End of variables declaration//GEN-END:variables
private void populateTable() {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        DefaultTableModel records = (DefaultTableModel) jTablehospname.getModel();
        records.setRowCount(0); //Clear empty records
        for(Hospital o : business.getHospitalDirectory().getHospitalList()){
            Object[] row = new Object[1];
            row[0] = o.getName();
            
            records.addRow(row);
        }
    }

}
