/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.CustomerRole;

import Project.SmartCity.Establishment.Theatre;
import Project.SmartCity.EstablishmentRoles.Customer;
import Project.SmartCity.SmartCity;
import Project.UserAccount.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Okami
 */
public class CustomerPlaceOrderTheatrePanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerPlaceOrderTheatrePanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private SmartCity business;
    Theatre theatre;
    Customer customer;
    public CustomerPlaceOrderTheatrePanel(JPanel userProcessContainer, UserAccount account, SmartCity business) {
        initComponents();
        this.business = business;
        this.userAccount = account;
        this.userProcessContainer = userProcessContainer;
        for (Customer c : business.getCustomerDirectory().getCustomerList()){
            if(c.getUsername().equals(userAccount.getUsername())){
                customer = c;
                break;
            }
        }
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableshop = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButtongoto = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableitems = new javax.swing.JTable();
        jTextFieldordercost = new javax.swing.JTextField();
        jButtonplaceordershop = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(251, 211, 245));

        jTableshop.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jTableshop.setForeground(new java.awt.Color(0, 51, 51));
        jTableshop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Name"
            }
        ));
        jScrollPane1.setViewportView(jTableshop);

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("Select Theatre:");

        jButtongoto.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jButtongoto.setForeground(new java.awt.Color(0, 51, 51));
        jButtongoto.setText(">>");
        jButtongoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtongotoActionPerformed(evt);
            }
        });

        jTableitems.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jTableitems.setForeground(new java.awt.Color(0, 51, 51));
        jTableitems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Movie", "Cost"
            }
        ));
        jTableitems.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableitemsMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTableitems);

        jTextFieldordercost.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jTextFieldordercost.setForeground(new java.awt.Color(0, 51, 51));

        jButtonplaceordershop.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jButtonplaceordershop.setForeground(new java.awt.Color(0, 51, 51));
        jButtonplaceordershop.setText("Book Tickets");
        jButtonplaceordershop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonplaceordershopActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("Total Cost:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jButtongoto, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(513, 513, 513)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldordercost, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addComponent(jButtonplaceordershop)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jButtongoto)))
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldordercost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(36, 36, 36)
                .addComponent(jButtonplaceordershop)
                .addContainerGap(165, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButtongotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtongotoActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = jTableshop.getSelectedRow();

        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a Theatre.");
            return;
        }

        DefaultTableModel records = (DefaultTableModel) jTableshop.getModel();
        String name = (String) records.getValueAt(selectedRowIndex, 0);

        theatre = business.getTheatreDirectory().getTheatre(name);
        populateTable2();
    }//GEN-LAST:event_jButtongotoActionPerformed

    private void jButtonplaceordershopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonplaceordershopActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = jTableitems.getSelectedRow();

        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a Movie.");
            return;
        }

        DefaultTableModel records = (DefaultTableModel) jTableitems.getModel();
        String name = (String) records.getValueAt(selectedRowIndex, 0);
        String cost = Integer.toString((int) records.getValueAt(selectedRowIndex, 1));
        
        customer.getTheatreDirectory().put(name, Integer.parseInt(cost));
        theatre.setRevenue(Integer.toString(Integer.parseInt(theatre.getRevenue())+Integer.parseInt(cost)));
        jTextFieldordercost.setText("");
        JOptionPane.showMessageDialog(this, "Ticket Booked.");
    }//GEN-LAST:event_jButtonplaceordershopActionPerformed

    private void jTableitemsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableitemsMousePressed
        // TODO add your handling code here:
        int selectedRowIndex = jTableitems.getSelectedRow();

        if(selectedRowIndex < 0){
            jTextFieldordercost.setText("");
            return;
        }

        DefaultTableModel records = (DefaultTableModel) jTableitems.getModel();
        String cost = Integer.toString((int) records.getValueAt(selectedRowIndex, 1));
        jTextFieldordercost.setText(cost);
    }//GEN-LAST:event_jTableitemsMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtongoto;
    private javax.swing.JButton jButtonplaceordershop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableitems;
    private javax.swing.JTable jTableshop;
    private javax.swing.JTextField jTextFieldordercost;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        DefaultTableModel records = (DefaultTableModel) jTableshop.getModel();
        records.setRowCount(0); //Clear empty records
        for(Theatre t : business.getTheatreDirectory().getTheatreList()){
            Object[] row = new Object[1];
            row[0] = t.getName();
            
            records.addRow(row);
        }
    }

    private void populateTable2() {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        
        DefaultTableModel records = (DefaultTableModel) jTableitems.getModel();
        records.setRowCount(0); //Clear empty records
        for(String s : theatre.getMovies().keySet()){
            Object[] row = new Object[2];
            row[0] = s;
            row[1] = theatre.getMovies().get(s);
            
            records.addRow(row);
        }
                
    }
}
