/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.SystemAdminWorkArea;
import Project.SmartCity.SmartCity;
import Project.SmartCity.TransportationSystem.Bus;
import Project.SmartCity.TransportationSystem.Cruise;
import Project.SmartCity.TransportationSystem.Flight;
import Project.SmartCity.TransportationSystem.Train;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.util.LinkedHashMap;
import java.util.Map;

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author latis
 */
public class HeadCountByTransportReport extends javax.swing.JPanel {
    
    public SmartCity business;
    public Bus bus;
    public static int BusHeadCount=0, TrainHeadCount=0, FlightHeadCount=0, CruiseHeadCount=0;

    private Map<Color, Integer> bars = new LinkedHashMap<Color, Integer>();
    /**
     * Creates new form HeadCountByTransportReport
     */
    
    public void addBar(Color color, int value)
	{
		bars.put(color, value);
		repaint();
	}
	
	@Override
	protected void paintComponent(Graphics g)
	{
		// determine longest bar
		
		int max = Integer.MIN_VALUE;
		for (Integer value : bars.values())
		{
			max = Math.max(max, value);
		}
		
		// paint bars
		
		int width = (getWidth() / bars.size()) - 2;
		int x = 1;
		for (Color color : bars.keySet())
		{
			int value = bars.get(color);
			int height = (int) 
                            ((getHeight()-5) * ((double)value / max));
			g.setColor(color);
			g.fillRect(x, getHeight() - height, width, height);
			g.setColor(Color.black);
			g.drawRect(x, getHeight() - height, width, height);
			x += (width + 2);
		}
	}

	@Override
	public Dimension getPreferredSize() {
		return new Dimension(bars.size() * 10 + 2, 50);
	}
        
        public static void main(String[] args)
	{
                JLabel jLabelBus = new JLabel();
                jLabelBus.setText("Bus");
                
		JFrame frame = new JFrame("Bar Chart");
		HeadCountByTransportReport chart = new HeadCountByTransportReport();
		chart.addBar(Color.pink, BusHeadCount);
		chart.addBar(Color.CYAN, TrainHeadCount);
		chart.addBar(Color.GRAY, FlightHeadCount);
		chart.addBar(Color.MAGENTA, CruiseHeadCount);	
                chart.add("Bus", jLabelBus);
		frame.getContentPane().add(chart);
		frame.pack();
		frame.setVisible(true);
                frame.setSize(2000/2, 800/2);
                frame.setLocation(659, 338);
	}

      
    
    public HeadCountByTransportReport(SmartCity business) {
        this.business = business;
                for (Bus b: business.getBusDirectory().getBusList()){
                    BusHeadCount = BusHeadCount + b.getUserCount();
                }
		for (Train t: business.getTrainDirectory().getTrainList()){
                    TrainHeadCount = TrainHeadCount + t.getUserCount();
                }
		for (Flight f: business.getFlightDirectory().getFlightList()){
                    FlightHeadCount = FlightHeadCount + f.getUserCount();
                }
		for (Cruise c: business.getCruiseDirectory().getCruiseList()){
                    CruiseHeadCount = CruiseHeadCount + c.getUserCount();
                }
                System.out.println("Bus Head Count = "+BusHeadCount);
		System.out.println("Train Head Count = "+TrainHeadCount);
		System.out.println("Flight Head Count = "+FlightHeadCount);
		System.out.println("Cruise Head Count = "+CruiseHeadCount);
                main(null);
    }
    public HeadCountByTransportReport(){
        initComponents();
        jLabel1.setText("Bus Headcount - "+BusHeadCount);
        jLabel2.setText("Train Headcount - "+TrainHeadCount);
        jLabel3.setText("Flight Headcount - "+FlightHeadCount);
        jLabel4.setText("Cruise Headcount - "+CruiseHeadCount);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setText("Mode - Bus");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setText("jLabel3");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(121, 121, 121)
                .addComponent(jLabel2)
                .addGap(101, 101, 101)
                .addComponent(jLabel3)
                .addGap(107, 107, 107)
                .addComponent(jLabel4)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(335, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(34, 34, 34))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
