/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.SystemAdminWorkArea;

import Project.SmartCity.SmartCity;
import Project.SmartCity.TourismSystem.TourismSystemRating;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author latis
 */
public class TourismRatingReport extends javax.swing.JPanel {

    /**
     * Creates new form TourismRatingReport
     */

    public TourismRatingReport(SmartCity business) {
        initComponents();
        TourismSystemRating tsr = new TourismSystemRating();
        float avg = business.getTourismSystemRating().AvgTourismSystemRating();
        System.out.println("Avg Rating"+avg+" TotalRating - "+tsr.getTotalRating()+" TotalCount - "+tsr.getCount());
        //float avg = 1.99f;
        if(avg < 1){
            jLabelRating.setIcon(new ImageIcon("/Users/harooniqbal/Desktop/AEDProjectImages/0Star.jpg"));
        }
        else if(avg >= 1 && avg <2){
            jLabelRating.setIcon(new ImageIcon("/Users/harooniqbal/Desktop/AEDProjectImages/1Star.jpg"));
        }
        else if(avg >= 2 && avg <3){
            jLabelRating.setIcon(new ImageIcon("/Users/harooniqbal/Desktop/AEDProjectImages/2Star.jpg"));
        }
        else if(avg >= 3 && avg <4){
            jLabelRating.setIcon(new ImageIcon("/Users/harooniqbal/Desktop/AEDProjectImages/3Star.jpg"));
        }
        else if(avg >= 4 && avg <5){
            jLabelRating.setIcon(new ImageIcon("/Users/harooniqbal/Desktop/AEDProjectImages/4Star.jpg"));
        }
        else if(avg ==5){
            jLabelRating.setIcon(new ImageIcon("/Users/harooniqbal/Desktop/AEDProjectImages/5Star.jpg"));
        }
        
    }
    public TourismRatingReport(){
        
    }
    
    
    public static void main(SmartCity business) {
        TourismRatingReport tsr = new TourismRatingReport(business);
        JFrame f=new JFrame();
        f.add(tsr);
        f.setVisible(true);
        f.setSize(2400/2, 1200/2);
        f.setLocation(659, 338);
        //JOptionPane.showMessageDialog(null,"Test");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelRating = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(0, 51, 51));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("Average Tourism System Rating");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabelRating))
                .addGap(197, 197, 197))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(96, 96, 96)
                .addComponent(jLabelRating)
                .addContainerGap(295, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelRating;
    // End of variables declaration//GEN-END:variables
}
