/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.PharmacistRole;

import Project.SmartCity.HealthcareRoles.Patient;
import Project.SmartCity.HealthcareRoles.Pharmacist;
import Project.SmartCity.HealthcareSystem.Pharmacy;
import Project.SmartCity.HealthcareSystem.Prescription;
import Project.SmartCity.SmartCity;
import Project.UserAccount.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author harooniqbal
 */
public class PharmacistProcessPrescriptionPanel extends javax.swing.JPanel {

    /**
     * Creates new form PharmacistProcessPrescriptionPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private SmartCity business;
    
    Pharmacist pharmacist;
    Pharmacy pharmacy;
    
    public PharmacistProcessPrescriptionPanel(JPanel userProcessContainer, UserAccount account, SmartCity business) {
        initComponents();
        this.business = business;
        this.userAccount = account;
        this.userProcessContainer = userProcessContainer;
        for (Pharmacy c : business.getPharmacyDirectory().getPharmacyList()){
            for(Pharmacist p : c.getPharmacistDirectory().getPharmacistList())
                if(p.getUsername().equals(userAccount.getUsername())){
                    pharmacist = p;
                    pharmacy = c;
                    break;
                }
        }
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTablepresctable = new javax.swing.JTable();
        jButtongoto1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablepharmname = new javax.swing.JTable();
        jButtongoto2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(206, 236, 206));
        setForeground(new java.awt.Color(0, 51, 51));

        jTablepresctable.setForeground(new java.awt.Color(0, 51, 51));
        jTablepresctable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Prescription ID", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTablepresctable);

        jButtongoto1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jButtongoto1.setForeground(new java.awt.Color(0, 51, 51));
        jButtongoto1.setText(">>");
        jButtongoto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtongoto1ActionPerformed(evt);
            }
        });

        jTablepharmname.setForeground(new java.awt.Color(0, 51, 51));
        jTablepharmname.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Drugs"
            }
        ));
        jScrollPane2.setViewportView(jTablepharmname);

        jButtongoto2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jButtongoto2.setForeground(new java.awt.Color(0, 51, 51));
        jButtongoto2.setText("Process Prescription");
        jButtongoto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtongoto2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(25, 56, 82));
        jLabel6.setText("PHARMACIST PROCESS PRESCRIPTION");

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 51));
        jLabel7.setText("Select Prescription:");

        jLabel11.setIcon(new javax.swing.ImageIcon("/Users/harooniqbal/Desktop/AEDProjectImages/pharmicon1.png")); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/harooniqbal/Desktop/AEDProjectImages/prescriptionbg.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(184, 184, 184)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jButtongoto1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(362, 362, 362)
                        .addComponent(jButtongoto2)))
                .addContainerGap(131, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel6))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addComponent(jLabel7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jButtongoto1)))
                .addGap(52, 52, 52)
                .addComponent(jButtongoto2)
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtongoto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtongoto1ActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = jTablepresctable.getSelectedRow();
        
        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a prescription.");
            return;
        }
        
        DefaultTableModel records = (DefaultTableModel) jTablepresctable.getModel();
        Integer id = (Integer) records.getValueAt(selectedRowIndex, 0);
        
        Prescription prescription = pharmacist.getPresdirectory().getPrescription(id);
        
        populateTable2(prescription);
    }//GEN-LAST:event_jButtongoto1ActionPerformed

    private void jButtongoto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtongoto2ActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = jTablepresctable.getSelectedRow();
        
        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a prescription.");
            return;
        }
        
        DefaultTableModel records = (DefaultTableModel) jTablepresctable.getModel();
        Integer id = (Integer) records.getValueAt(selectedRowIndex, 0);
        
        Prescription prescription = pharmacist.getPresdirectory().getPrescription(id);
        
        Patient patient;
        Prescription prescription1 = new Prescription();
        
        for(Patient p : pharmacy.getPatientDirectory().getPatientList()){
            for(Prescription i : p.getPresdirectory().getPrescriptionList()){
                if(i.equals(prescription)){
                   patient = p;
                   prescription1 = i;
                }
            }
        }
        
        prescription.setStatus("Completed");
        prescription1.setStatus("Completed");
        
        populateTable();
        JOptionPane.showMessageDialog(this, "Prescription Processed.");
    }//GEN-LAST:event_jButtongoto2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtongoto1;
    private javax.swing.JButton jButtongoto2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTablepharmname;
    private javax.swing.JTable jTablepresctable;
    // End of variables declaration//GEN-END:variables
private void populateTable() {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        
        DefaultTableModel records = (DefaultTableModel) jTablepresctable.getModel();
        records.setRowCount(0); //Clear empty records
        for(Prescription o : pharmacist.getPresdirectory().getPrescriptionList()){
            Object[] row = new Object[2];
            row[0] = o.getId();
            row[1] = o.getStatus();
            records.addRow(row);
        }
    }

    private void populateTable2(Prescription prescription) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        
        DefaultTableModel records = (DefaultTableModel) jTablepharmname.getModel();
        records.setRowCount(0); //Clear empty records
        for(String o : prescription.getDrugs()){
            Object[] row = new Object[1];
            row[0] = o;
            records.addRow(row);
        }        
    }
}
