/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.TouristRole;

import Project.SmartCity.SmartCity;
import Project.UserAccount.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author harooniqbal
 */
public class TouristGiveRatingPanel extends javax.swing.JPanel {

    /**
     * Creates new form TouristGiveRatingPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private SmartCity business;
    
    String type = "";
    public TouristGiveRatingPanel(JPanel userProcessContainer, UserAccount account, SmartCity business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jRadioButtonamazing1 = new javax.swing.JRadioButton();
        jRadioButtonneutral1 = new javax.swing.JRadioButton();
        jRadioButtongood1 = new javax.swing.JRadioButton();
        jRadioButtonbad1 = new javax.swing.JRadioButton();
        jRadioButtonworst1 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jRadioButtonrate5 = new javax.swing.JRadioButton();
        jRadioButtonrate4 = new javax.swing.JRadioButton();
        jRadioButtonrate3 = new javax.swing.JRadioButton();
        jRadioButtonrate2 = new javax.swing.JRadioButton();
        jRadioButtonrate1 = new javax.swing.JRadioButton();
        jRadioButtonamazing2 = new javax.swing.JRadioButton();
        jRadioButtongood2 = new javax.swing.JRadioButton();
        jRadioButtonneutral2 = new javax.swing.JRadioButton();
        jRadioButtonbad2 = new javax.swing.JRadioButton();
        jRadioButtonworst2 = new javax.swing.JRadioButton();
        submitbtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(194, 216, 220));

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("1) How was your overall tourism experience?");

        jRadioButtonamazing1.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jRadioButtonamazing1.setForeground(new java.awt.Color(0, 51, 51));
        jRadioButtonamazing1.setText("Amazing");

        jRadioButtonneutral1.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jRadioButtonneutral1.setForeground(new java.awt.Color(0, 51, 51));
        jRadioButtonneutral1.setText("Neutral");

        jRadioButtongood1.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jRadioButtongood1.setForeground(new java.awt.Color(0, 51, 51));
        jRadioButtongood1.setText("Good");

        jRadioButtonbad1.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jRadioButtonbad1.setForeground(new java.awt.Color(0, 51, 51));
        jRadioButtonbad1.setText("Bad");

        jRadioButtonworst1.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jRadioButtonworst1.setForeground(new java.awt.Color(0, 51, 51));
        jRadioButtonworst1.setText("Worst");

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 51));
        jLabel4.setText("3) Would you recommend this package?");

        jRadioButtonrate5.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jRadioButtonrate5.setForeground(new java.awt.Color(0, 51, 51));
        jRadioButtonrate5.setText("5");

        jRadioButtonrate4.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jRadioButtonrate4.setForeground(new java.awt.Color(0, 51, 51));
        jRadioButtonrate4.setText("4");

        jRadioButtonrate3.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jRadioButtonrate3.setForeground(new java.awt.Color(0, 51, 51));
        jRadioButtonrate3.setText("3");

        jRadioButtonrate2.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jRadioButtonrate2.setForeground(new java.awt.Color(0, 51, 51));
        jRadioButtonrate2.setText("2");

        jRadioButtonrate1.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jRadioButtonrate1.setForeground(new java.awt.Color(0, 51, 51));
        jRadioButtonrate1.setText("1");
        jRadioButtonrate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonrate1ActionPerformed(evt);
            }
        });

        jRadioButtonamazing2.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jRadioButtonamazing2.setForeground(new java.awt.Color(0, 51, 51));
        jRadioButtonamazing2.setText("Strongly Disagree");

        jRadioButtongood2.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jRadioButtongood2.setForeground(new java.awt.Color(0, 51, 51));
        jRadioButtongood2.setText("Disagree");

        jRadioButtonneutral2.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jRadioButtonneutral2.setForeground(new java.awt.Color(0, 51, 51));
        jRadioButtonneutral2.setText("Neutral");

        jRadioButtonbad2.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jRadioButtonbad2.setForeground(new java.awt.Color(0, 51, 51));
        jRadioButtonbad2.setText("Agree");

        jRadioButtonworst2.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jRadioButtonworst2.setForeground(new java.awt.Color(0, 51, 51));
        jRadioButtonworst2.setText("Strongly Agree");

        submitbtn.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        submitbtn.setForeground(new java.awt.Color(0, 51, 51));
        submitbtn.setText("Submit");
        submitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbtnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 51));
        jLabel5.setText("2) How much would you rate your experience on a scale of 1 to 5?");

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(25, 56, 82));
        jLabel6.setText("TOURIST FEEDBACK FORM");

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/harooniqbal/Desktop/AEDProjectImages/touristfeedbackfinal.png")); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon("/Users/harooniqbal/Desktop/AEDProjectImages/feedbackicon.png")); // NOI18N
        jLabel10.setText("jLabel10");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButtonamazing1)
                                .addGap(32, 32, 32)
                                .addComponent(jRadioButtongood1)
                                .addGap(37, 37, 37)
                                .addComponent(jRadioButtonneutral1)
                                .addGap(35, 35, 35)
                                .addComponent(jRadioButtonbad1)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonworst1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonworst2)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jRadioButtonrate1)
                                        .addGap(43, 43, 43)
                                        .addComponent(jRadioButtonrate2)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jRadioButtonrate3)
                                        .addGap(40, 40, 40)
                                        .addComponent(jRadioButtonrate4)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButtonrate5))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jRadioButtonbad2)
                                        .addGap(34, 34, 34)
                                        .addComponent(jRadioButtonneutral2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButtongood2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButtonamazing2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(286, 286, 286)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(380, 380, 380)
                .addComponent(submitbtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(565, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(248, 248, 248))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel6))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonamazing1)
                    .addComponent(jRadioButtonworst1)
                    .addComponent(jRadioButtongood1)
                    .addComponent(jRadioButtonneutral1)
                    .addComponent(jRadioButtonbad1))
                .addGap(39, 39, 39)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonrate1)
                    .addComponent(jRadioButtonrate2)
                    .addComponent(jRadioButtonrate3)
                    .addComponent(jRadioButtonrate4)
                    .addComponent(jRadioButtonrate5))
                .addGap(40, 40, 40)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonworst2)
                    .addComponent(jRadioButtonbad2)
                    .addComponent(jRadioButtonneutral2)
                    .addComponent(jRadioButtongood2)
                    .addComponent(jRadioButtonamazing2))
                .addGap(61, 61, 61)
                .addComponent(submitbtn)
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(334, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonrate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonrate1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonrate1ActionPerformed

    private void submitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Thank you for submitting your feedback.");
    }//GEN-LAST:event_submitbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonamazing1;
    private javax.swing.JRadioButton jRadioButtonamazing2;
    private javax.swing.JRadioButton jRadioButtonbad1;
    private javax.swing.JRadioButton jRadioButtonbad2;
    private javax.swing.JRadioButton jRadioButtongood1;
    private javax.swing.JRadioButton jRadioButtongood2;
    private javax.swing.JRadioButton jRadioButtonneutral1;
    private javax.swing.JRadioButton jRadioButtonneutral2;
    private javax.swing.JRadioButton jRadioButtonrate1;
    private javax.swing.JRadioButton jRadioButtonrate2;
    private javax.swing.JRadioButton jRadioButtonrate3;
    private javax.swing.JRadioButton jRadioButtonrate4;
    private javax.swing.JRadioButton jRadioButtonrate5;
    private javax.swing.JRadioButton jRadioButtonworst1;
    private javax.swing.JRadioButton jRadioButtonworst2;
    private javax.swing.JButton submitbtn;
    // End of variables declaration//GEN-END:variables
}
