/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.CommuterRole;

import Project.SmartCity.SmartCity;
import Project.SmartCity.TransportationRoles.Commuter;
import Project.SmartCity.TransportationSystem.Bus;
import Project.SmartCity.TransportationSystem.BusDirectory;
import Project.SmartCity.TransportationSystem.Cruise;
import Project.SmartCity.TransportationSystem.CruiseDirectory;
import Project.SmartCity.TransportationSystem.Flight;
import Project.SmartCity.TransportationSystem.FlightDirectory;
import Project.SmartCity.TransportationSystem.Ticket;
import Project.SmartCity.TransportationSystem.Train;
import Project.SmartCity.TransportationSystem.TrainDirectory;
import Project.UserAccount.UserAccount;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author harooniqbal
 */
public class CommuterBookTicketsPanel extends javax.swing.JPanel {

    /**
     * Creates new form CommuterBookTicketsPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private SmartCity business;
    
    Commuter commuter;
    String type = "";
    
    public CommuterBookTicketsPanel(JPanel userProcessContainer, UserAccount account, SmartCity business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.business = business;
        for (Commuter c : business.getCommuterDirectory().getCommuterList()){
            if(c.getUsername().equals(userAccount.getUsername())){
                commuter = c;
                break;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonbus = new javax.swing.JButton();
        jButtontrain = new javax.swing.JButton();
        jButtonflight = new javax.swing.JButton();
        jButtoncruise = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButtonbus1 = new javax.swing.JButton();
        jButtontrain1 = new javax.swing.JButton();
        jButtonflight1 = new javax.swing.JButton();
        jButtoncruise1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablecommuterviewservices = new javax.swing.JTable();
        jButtonbookticket = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jButtonbus.setText("Bus");

        jButtontrain.setText("Train");

        jButtonflight.setText("Flight");

        jButtoncruise.setText("Cruise");

        jLabel10.setIcon(new javax.swing.ImageIcon("/Users/harooniqbal/Desktop/AEDProjectImages/tourismicon-removebg-preview (1).png")); // NOI18N
        jLabel10.setText("jLabel10");

        setBackground(new java.awt.Color(253, 232, 215));
        setForeground(new java.awt.Color(0, 51, 51));

        jButtonbus1.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jButtonbus1.setForeground(new java.awt.Color(0, 51, 51));
        jButtonbus1.setIcon(new javax.swing.ImageIcon("/Users/harooniqbal/Desktop/AEDProjectImages/Bus (1).png")); // NOI18N
        jButtonbus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonbus1ActionPerformed(evt);
            }
        });

        jButtontrain1.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jButtontrain1.setForeground(new java.awt.Color(0, 51, 51));
        jButtontrain1.setIcon(new javax.swing.ImageIcon("/Users/harooniqbal/Desktop/AEDProjectImages/Train (1).png")); // NOI18N
        jButtontrain1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtontrain1ActionPerformed(evt);
            }
        });

        jButtonflight1.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jButtonflight1.setForeground(new java.awt.Color(0, 51, 51));
        jButtonflight1.setIcon(new javax.swing.ImageIcon("/Users/harooniqbal/Desktop/AEDProjectImages/Flight (1).png")); // NOI18N
        jButtonflight1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonflight1ActionPerformed(evt);
            }
        });

        jButtoncruise1.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jButtoncruise1.setForeground(new java.awt.Color(0, 51, 51));
        jButtoncruise1.setIcon(new javax.swing.ImageIcon("/Users/harooniqbal/Desktop/AEDProjectImages/Cruise_3 (1).png")); // NOI18N
        jButtoncruise1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncruise1ActionPerformed(evt);
            }
        });

        jScrollPane1.setForeground(new java.awt.Color(0, 51, 51));

        jTablecommuterviewservices.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jTablecommuterviewservices.setForeground(new java.awt.Color(0, 51, 51));
        jTablecommuterviewservices.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Number", "Start Location", "Drop Location"
            }
        ));
        jScrollPane1.setViewportView(jTablecommuterviewservices);

        jButtonbookticket.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jButtonbookticket.setForeground(new java.awt.Color(0, 51, 51));
        jButtonbookticket.setText("Book Ticket");
        jButtonbookticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonbookticketActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(253, 225, 196));
        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("Select Date of Journey:");

        jDateChooser1.setBackground(new java.awt.Color(253, 225, 196));
        jDateChooser1.setForeground(new java.awt.Color(0, 51, 51));
        jDateChooser1.setDateFormatString("MMM d, yyyy");

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(25, 56, 82));
        jLabel4.setText("COMMUTER BOOK TICKETS");

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("Select Vehicle Details:");

        jLabel11.setIcon(new javax.swing.ImageIcon("/Users/harooniqbal/Desktop/AEDProjectImages/CommuterBookTicketsLogo - Copy.png")); // NOI18N
        jLabel11.setText("jLabel10");

        jLabel3.setIcon(new javax.swing.ImageIcon("/Users/harooniqbal/Desktop/AEDProjectImages/CommuterBookTickets_BG.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(538, 538, 538))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jButtonbus1)
                        .addGap(54, 54, 54)
                        .addComponent(jButtontrain1)
                        .addGap(61, 61, 61)
                        .addComponent(jButtonflight1)
                        .addGap(73, 73, 73)
                        .addComponent(jButtoncruise1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(348, 348, 348)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(33, 33, 33)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jButtonbookticket)))
                .addGap(139, 139, 139)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel4)
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonbus1)
                            .addComponent(jButtonflight1)
                            .addComponent(jButtoncruise1)
                            .addComponent(jButtontrain1)))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46)
                .addComponent(jButtonbookticket)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonbus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonbus1ActionPerformed
        // TODO add your handling code here:
        type = "Bus";
        populateTable();
         JOptionPane.showMessageDialog(this, "Bus selected");
    }//GEN-LAST:event_jButtonbus1ActionPerformed

    private void jButtontrain1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtontrain1ActionPerformed
        // TODO add your handling code here:
        type = "Train";
        populateTable();
         JOptionPane.showMessageDialog(this, "Train selected");
    }//GEN-LAST:event_jButtontrain1ActionPerformed

    private void jButtonflight1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonflight1ActionPerformed
        // TODO add your handling code here:
        type = "Flight";
        populateTable();
         JOptionPane.showMessageDialog(this, "Flight selected");
    }//GEN-LAST:event_jButtonflight1ActionPerformed

    private void jButtoncruise1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncruise1ActionPerformed
        // TODO add your handling code here:
        type = "Cruise";
        populateTable();
         JOptionPane.showMessageDialog(this, "Cruise selected.");
    }//GEN-LAST:event_jButtoncruise1ActionPerformed

    private void jButtonbookticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonbookticketActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = jTablecommuterviewservices.getSelectedRow();
        
        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a ride to be booked.");
            return;
        }
        
        DefaultTableModel records = (DefaultTableModel) jTablecommuterviewservices.getModel();
        Integer id = (Integer) records.getValueAt(selectedRowIndex, 0);
        
        Date d = jDateChooser1.getDate();  
        DateFormat dateFormat = new SimpleDateFormat("MMM d, yyyy");  
        String date = dateFormat.format(d);  
        
        switch(type){
            case "Bus":
                Bus bus = business.getBusDirectory().getBus(id);
                commuter.getTicketList().createTicket("Bus", bus.getNumber(), date, bus.getStartLocation(), bus.getDropLocation());
                break;
            case "Train":
                Train train = business.getTrainDirectory().getTrain(id);
                commuter.getTicketList().createTicket("Train", train.getNumber(), date, train.getStartLocation(), train.getDropLocation());
                break;
            case "Flight":
                Flight flight = business.getFlightDirectory().getFlight(id);
                commuter.getTicketList().createTicket("Flight", flight.getNumber(), date, flight.getStartLocation(), flight.getDropLocation());
                break;
            case "Cruise":
                Cruise cruise = business.getCruiseDirectory().getCruise(id);
                commuter.getTicketList().createTicket("Cruise", cruise.getNumber(), date, cruise.getStartLocation(), cruise.getDropLocation());
                break;
            default:
                JOptionPane.showMessageDialog(this, "Please select either a bus, train, flight, or a cruise.");
                return;
        }
         JOptionPane.showMessageDialog(this, "Ticket booked.");
    }//GEN-LAST:event_jButtonbookticketActionPerformed

    private void populateTable() {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        
        DefaultTableModel records = (DefaultTableModel) jTablecommuterviewservices.getModel();
        
        switch(type){
            case "Bus":
                BusDirectory busDirectory = business.getBusDirectory();
                records.setRowCount(0); //Clear empty records

                for(Bus o : busDirectory.getBusList()){
                        Object[] row = new Object[4];
                        row[0] = o.getId();
                        //row[0] = vs.getDate();
                        row[1] = o.getNumber();
                        row[2] = o.getStartLocation();
                        row[3] = o.getDropLocation();

                        records.addRow(row);
                }
                break;
            case "Train":
                TrainDirectory trainDirectory = business.getTrainDirectory();
                records.setRowCount(0); //Clear empty records

                for(Train o : trainDirectory.getTrainList()){
                        Object[] row = new Object[4];
                        row[0] = o.getId();
                        //row[0] = vs.getDate();
                        row[1] = o.getNumber();
                        row[2] = o.getStartLocation();
                        row[3] = o.getDropLocation();

                        records.addRow(row);
                }
                break;
            case "Flight":
                FlightDirectory flightDirectory = business.getFlightDirectory();
                records.setRowCount(0); //Clear empty records

                for(Flight o : flightDirectory.getFlightList()){
                        Object[] row = new Object[4];
                        row[0] = o.getId();
                        //row[0] = vs.getDate();
                        row[1] = o.getNumber();
                        row[2] = o.getStartLocation();
                        row[3] = o.getDropLocation();

                        records.addRow(row);
                }
                break;
            case "Cruise":
                CruiseDirectory cruiseDirectory = business.getCruiseDirectory();
                records.setRowCount(0); //Clear empty records

                for(Cruise o : cruiseDirectory.getCruiseList()){
                        Object[] row = new Object[4];
                        row[0] = o.getId();
                        //row[0] = vs.getDate();
                        row[1] = o.getNumber();
                        row[2] = o.getStartLocation();
                        row[3] = o.getDropLocation();

                        records.addRow(row);
                }
                break;
            default:
                JOptionPane.showMessageDialog(this, "Please select either a bus, train,  or a restaurant.");
                return;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonbookticket;
    private javax.swing.JButton jButtonbus;
    private javax.swing.JButton jButtonbus1;
    private javax.swing.JButton jButtoncruise;
    private javax.swing.JButton jButtoncruise1;
    private javax.swing.JButton jButtonflight;
    private javax.swing.JButton jButtonflight1;
    private javax.swing.JButton jButtontrain;
    private javax.swing.JButton jButtontrain1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablecommuterviewservices;
    // End of variables declaration//GEN-END:variables
}
