/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.CommuterRole;

import Project.SmartCity.SmartCity;
import Project.SmartCity.TransportationRoles.Commuter;
import Project.SmartCity.TransportationSystem.Bus;
import Project.SmartCity.TransportationSystem.BusDirectory;
import Project.SmartCity.TransportationSystem.Cruise;
import Project.SmartCity.TransportationSystem.CruiseDirectory;
import Project.SmartCity.TransportationSystem.Flight;
import Project.SmartCity.TransportationSystem.FlightDirectory;
import Project.SmartCity.TransportationSystem.Ticket;
import Project.SmartCity.TransportationSystem.Train;
import Project.SmartCity.TransportationSystem.TrainDirectory;
import Project.UserAccount.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author harooniqbal
 */
public class CommuterViewHistoryPanel extends javax.swing.JPanel {

    /**
     * Creates new form CommuterViewHistoryPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private SmartCity business;
    
    Commuter commuter;
    String type = "";
    
    public CommuterViewHistoryPanel(JPanel userProcessContainer, UserAccount account, SmartCity business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.business = business;
        for (Commuter c : business.getCommuterDirectory().getCommuterList()){
            if(c.getUsername().equals(userAccount.getUsername())){
                commuter = c;
                break;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonbus = new javax.swing.JButton();
        jButtontrain = new javax.swing.JButton();
        jButtonflight = new javax.swing.JButton();
        jButtoncruise = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablecommuterviewservices = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(253, 232, 215));
        setForeground(new java.awt.Color(0, 51, 51));

        jButtonbus.setFont(new java.awt.Font(".SF NS Text", 0, 14)); // NOI18N
        jButtonbus.setForeground(new java.awt.Color(0, 51, 51));
        jButtonbus.setIcon(new javax.swing.ImageIcon("/Users/harooniqbal/Desktop/AEDProjectImages/Bus (1).png")); // NOI18N
        jButtonbus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonbusActionPerformed(evt);
            }
        });

        jButtontrain.setFont(new java.awt.Font(".SF NS Text", 0, 14)); // NOI18N
        jButtontrain.setForeground(new java.awt.Color(0, 51, 51));
        jButtontrain.setIcon(new javax.swing.ImageIcon("/Users/harooniqbal/Desktop/AEDProjectImages/Train (1).png")); // NOI18N
        jButtontrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtontrainActionPerformed(evt);
            }
        });

        jButtonflight.setFont(new java.awt.Font(".SF NS Text", 0, 14)); // NOI18N
        jButtonflight.setForeground(new java.awt.Color(0, 51, 51));
        jButtonflight.setIcon(new javax.swing.ImageIcon("/Users/harooniqbal/Desktop/AEDProjectImages/Flight (1).png")); // NOI18N
        jButtonflight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonflightActionPerformed(evt);
            }
        });

        jButtoncruise.setFont(new java.awt.Font(".SF NS Text", 0, 14)); // NOI18N
        jButtoncruise.setForeground(new java.awt.Color(0, 51, 51));
        jButtoncruise.setIcon(new javax.swing.ImageIcon("/Users/harooniqbal/Desktop/AEDProjectImages/Cruise_3 (1).png")); // NOI18N
        jButtoncruise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncruiseActionPerformed(evt);
            }
        });

        jScrollPane1.setForeground(new java.awt.Color(0, 51, 51));

        jTablecommuterviewservices.setForeground(new java.awt.Color(0, 51, 51));
        jTablecommuterviewservices.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Number", "Start Location", "Drop Location"
            }
        ));
        jScrollPane1.setViewportView(jTablecommuterviewservices);

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(25, 56, 82));
        jLabel6.setText("COMMUTER VIEW TICKET HISTORY");

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/harooniqbal/Desktop/AEDProjectImages/commuterviewhist.png")); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon("/Users/harooniqbal/Desktop/AEDProjectImages/commuterviewhisticon.png")); // NOI18N
        jLabel10.setText("jLabel10");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(188, 188, 188)
                                .addComponent(jButtonbus)
                                .addGap(66, 66, 66)
                                .addComponent(jButtontrain)
                                .addGap(73, 73, 73)
                                .addComponent(jButtonflight)))
                        .addGap(86, 86, 86)
                        .addComponent(jButtoncruise)))
                .addContainerGap(212, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonbus, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonflight, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtoncruise, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtontrain, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonbusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonbusActionPerformed
        // TODO add your handling code here:
        type = "Bus";
        populateTable();
    }//GEN-LAST:event_jButtonbusActionPerformed

    private void jButtontrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtontrainActionPerformed
        // TODO add your handling code here:
        type = "Train";
        populateTable();
    }//GEN-LAST:event_jButtontrainActionPerformed

    private void jButtonflightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonflightActionPerformed
        // TODO add your handling code here:
        type = "Flight";
        populateTable();
    }//GEN-LAST:event_jButtonflightActionPerformed

    private void jButtoncruiseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncruiseActionPerformed
        // TODO add your handling code here:
        type = "Cruise";
        populateTable();
    }//GEN-LAST:event_jButtoncruiseActionPerformed

    private void populateTable() {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        DefaultTableModel records = (DefaultTableModel) jTablecommuterviewservices.getModel();
        
        switch(type){
            case "Bus":
                records.setRowCount(0); //Clear empty records
                for(Ticket o : commuter.getTicketList().getTicketList()){
                    if(o.getMode().equals("Bus")){    
                        Object[] row = new Object[4];
                        row[0] = o.getId();
                        //row[0] = vs.getDate();
                        row[1] = "Bus-"+o.getVehiclenumber();
                        row[2] = o.getStartlocation();
                        row[3] = o.getDroplocation();

                        records.addRow(row);
                    }
                }
                break;
            case "Train":
                TrainDirectory trainDirectory = business.getTrainDirectory();
                records.setRowCount(0); //Clear empty records
                for(Ticket o : commuter.getTicketList().getTicketList()){
                    if(o.getMode().equals("Train")){    
                        Object[] row = new Object[4];
                        row[0] = o.getId();
                        //row[0] = vs.getDate();
                        row[1] = "Train-"+o.getVehiclenumber();
                        row[2] = o.getStartlocation();
                        row[3] = o.getDroplocation();

                        records.addRow(row);
                    }
                }
                break;
            case "Flight":
                FlightDirectory flightDirectory = business.getFlightDirectory();
                records.setRowCount(0); //Clear empty records
                for(Ticket o : commuter.getTicketList().getTicketList()){
                    if(o.getMode().equals("Flight")){    
                        Object[] row = new Object[4];
                        row[0] = o.getId();
                        //row[0] = vs.getDate();
                        row[1] = "Flight-"+o.getVehiclenumber();
                        row[2] = o.getStartlocation();
                        row[3] = o.getDroplocation();

                        records.addRow(row);
                    }
                }
                break;
            case "Cruise":
                CruiseDirectory cruiseDirectory = business.getCruiseDirectory();
                records.setRowCount(0); //Clear empty records
                for(Ticket o : commuter.getTicketList().getTicketList()){
                    if(o.getMode().equals("Cruise")){    
                        Object[] row = new Object[4];
                        row[0] = o.getId();
                        //row[0] = vs.getDate();
                        row[1] = "Cruise-"+o.getVehiclenumber();
                        row[2] = o.getStartlocation();
                        row[3] = o.getDroplocation();

                        records.addRow(row);
                    }
                }
                break;
            default:
                JOptionPane.showMessageDialog(this, "Please select either bus, train, flight or a cruise.");
                return;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonbus;
    private javax.swing.JButton jButtoncruise;
    private javax.swing.JButton jButtonflight;
    private javax.swing.JButton jButtontrain;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablecommuterviewservices;
    // End of variables declaration//GEN-END:variables
}
