/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.BusinessOwnerRole;

import Project.SmartCity.Establishment.Restaurant;
import Project.SmartCity.Establishment.RestaurantDirectory;
import Project.SmartCity.Establishment.Shop;
import Project.SmartCity.Establishment.ShopDirectory;
import Project.SmartCity.SmartCity;
import Project.UserAccount.UserAccount;
import java.awt.Image;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author harooniqbal
 */
public class BusinessOwnerViewBusinessesPanel extends javax.swing.JPanel {

    /**
     * Creates new form BusinessOwnerViewBusinessesPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private SmartCity business;
    String type="";
    
    public BusinessOwnerViewBusinessesPanel(JPanel userProcessContainer, UserAccount account, SmartCity business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonshops = new javax.swing.JButton();
        jButtonrestaurants = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablebusownerviewbusiness = new javax.swing.JTable();
        jButtonrestaurants1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(251, 211, 245));
        setForeground(new java.awt.Color(0, 51, 51));

        jButtonshops.setIcon(new javax.swing.ImageIcon("/Users/harooniqbal/Desktop/AEDProjectImages/shopitemsicon.png")); // NOI18N
        jButtonshops.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonshopsActionPerformed(evt);
            }
        });

        jButtonrestaurants.setIcon(new javax.swing.ImageIcon("/Users/harooniqbal/Desktop/AEDProjectImages/restbtn.png")); // NOI18N
        jButtonrestaurants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonrestaurantsActionPerformed(evt);
            }
        });

        jTablebusownerviewbusiness.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Location", "Revenue"
            }
        ));
        jScrollPane1.setViewportView(jTablebusownerviewbusiness);

        jButtonrestaurants1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jButtonrestaurants1.setForeground(new java.awt.Color(0, 51, 51));
        jButtonrestaurants1.setText("Show Location");
        jButtonrestaurants1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonrestaurants1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(25, 56, 82));
        jLabel6.setText("BUSINESS OWNER VIEW BUSINESS PANEL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonshops, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(105, 105, 105)
                                .addComponent(jButtonrestaurants, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addComponent(jButtonrestaurants1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(jLabel6)))
                .addContainerGap(376, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel6)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonshops, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonrestaurants, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jButtonrestaurants1)
                .addContainerGap(273, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonshopsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonshopsActionPerformed
        // TODO add your handling code here:
        ShopDirectory shopDirectory = business.getShopDirectory();
        DefaultTableModel records = (DefaultTableModel) jTablebusownerviewbusiness.getModel();
        records.setRowCount(0); //Clear empty records
        
        for(Shop o : shopDirectory.getShopList()){
            if(o.getUsername().equals(userAccount.getUsername())){
                Object[] row = new Object[4];
                row[0] = o.getId();
                //row[0] = vs.getDate();
                row[1] = o.getName();
                row[2] = o.getLocation()[0]+"/"+o.getLocation()[1];
                row[3] = o.getRevenue();
                
                records.addRow(row);
            }
        }
        type = "Shop";
    }//GEN-LAST:event_jButtonshopsActionPerformed

    private void jButtonrestaurantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonrestaurantsActionPerformed
        // TODO add your handling code here:
        RestaurantDirectory restaurantDirectory = business.getRestaurantDirectory();
        DefaultTableModel records = (DefaultTableModel) jTablebusownerviewbusiness.getModel();
        records.setRowCount(0); //Clear empty records
        
        for(Restaurant o : restaurantDirectory.getRestaurantList()){
            if(o.getUsername().equals(userAccount.getUsername())){
                Object[] row = new Object[4];
                row[0] = o.getId();
                //row[0] = vs.getDate();
                row[1] = o.getName();
                row[2] = o.getLocation()[0]+"/"+o.getLocation()[1];
                row[3] = o.getRevenue();
                
                records.addRow(row);
            }
        }
        type = "Restaurant";
    }//GEN-LAST:event_jButtonrestaurantsActionPerformed

    private void jButtonrestaurants1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonrestaurants1ActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = jTablebusownerviewbusiness.getSelectedRow();
        
        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a row to be viewed.");
            return;
        }
        
        DefaultTableModel records = (DefaultTableModel) jTablebusownerviewbusiness.getModel();
        String name = (String) records.getValueAt(selectedRowIndex, 1);
        if(type.equals("Shop")){
            Shop shop = business.getShopDirectory().getShop(name);
            Image image1 = null;
            URL url=null;
            try {
                url = new URL("https://maps.googleapis.com/maps/api/staticmap?center="+shop.location[0]+","+shop.location[1]+"&zoom=10&size=400x400&markers=color:red%7Clabel:G%7C"+shop.location[0]+","+shop.location[1]+"&key=AIzaSyBBMO7Tcty1cgtbP3zw7VZpv8juNlq_dLo");
                image1 = ImageIO.read(url);
            } catch (MalformedURLException ex) {
                Logger.getLogger(BusinessOwnerViewBusinessesPanel.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(BusinessOwnerViewBusinessesPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            JFrame f = new JFrame();
        //f.setUndecorated(true);
            ImageIcon image = new ImageIcon(image1);
            JLabel lbl = new JLabel(image);
            f.getContentPane().add(lbl);
            f.setSize(1200/2, 800/2);
            f.setLocation(659, 338);
            f.setVisible(true);
        }
        else if(type.equals("Restaurant")){
            Restaurant restaurant = business.getRestaurantDirectory().getRestaurant(name);
            Image image1 = null;
            URL url=null;
            try {
                url = new URL("https://maps.googleapis.com/maps/api/staticmap?center="+restaurant.location[0]+","+restaurant.location[1]+"&zoom=10&size=400x400&markers=color:red%7Clabel:G%7C"+restaurant.location[0]+","+restaurant.location[1]+"&key=AIzaSyBBMO7Tcty1cgtbP3zw7VZpv8juNlq_dLo");
                image1 = ImageIO.read(url);
            } catch (MalformedURLException ex) {
                Logger.getLogger(BusinessOwnerViewBusinessesPanel.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(BusinessOwnerViewBusinessesPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            JFrame f = new JFrame();
        //f.setUndecorated(true);
            ImageIcon image = new ImageIcon(image1);
            JLabel lbl = new JLabel(image);
            f.getContentPane().add(lbl);
            f.setSize(1200/2, 800/2);
            f.setLocation(659, 338);
            f.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(this, "Please select either a shop or a restaurant.");
            return;
        }
       // JOptionPane.showMessageDialog(this, "Business viewed");

    }//GEN-LAST:event_jButtonrestaurants1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonrestaurants;
    private javax.swing.JButton jButtonrestaurants1;
    private javax.swing.JButton jButtonshops;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablebusownerviewbusiness;
    // End of variables declaration//GEN-END:variables
}
