/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UI.BusinessOwnerRole;

import Project.SmartCity.Establishment.Restaurant;
import Project.SmartCity.Establishment.Shop;
import Project.SmartCity.SmartCity;
import Project.UserAccount.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author harooniqbal
 */
public class BusinessOwnerAddBusinessPanel extends javax.swing.JPanel {

    /** Creates new form BusinessOwnerAddBusinessPanel */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private SmartCity business;
    String type = "";
    String[] location;
    
    public BusinessOwnerAddBusinessPanel(JPanel userProcessContainer, UserAccount account, SmartCity business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.business = business;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonshops = new javax.swing.JButton();
        jButtonrestaurants = new javax.swing.JButton();
        jButtonsetlocation = new javax.swing.JButton();
        jLabelbusinessname = new javax.swing.JLabel();
        jLabelbusinesslocation = new javax.swing.JLabel();
        jTextFieldbusinessname = new javax.swing.JTextField();
        jTextFieldbusinesslocation = new javax.swing.JTextField();
        jButtonaddbusiness = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(251, 211, 245));

        jButtonshops.setIcon(new javax.swing.ImageIcon("/Users/harooniqbal/Desktop/AEDProjectImages/shopitemsicon.png")); // NOI18N
        jButtonshops.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonshopsActionPerformed(evt);
            }
        });

        jButtonrestaurants.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jButtonrestaurants.setIcon(new javax.swing.ImageIcon("/Users/harooniqbal/Desktop/AEDProjectImages/restbtn.png")); // NOI18N
        jButtonrestaurants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonrestaurantsActionPerformed(evt);
            }
        });

        jButtonsetlocation.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jButtonsetlocation.setForeground(new java.awt.Color(0, 51, 51));
        jButtonsetlocation.setText("Set Location");
        jButtonsetlocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsetlocationActionPerformed(evt);
            }
        });

        jLabelbusinessname.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabelbusinessname.setForeground(new java.awt.Color(0, 51, 51));
        jLabelbusinessname.setText("Name:");

        jLabelbusinesslocation.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabelbusinesslocation.setForeground(new java.awt.Color(0, 51, 51));
        jLabelbusinesslocation.setText("Location:");

        jTextFieldbusinessname.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jTextFieldbusinessname.setForeground(new java.awt.Color(0, 51, 51));

        jTextFieldbusinesslocation.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jTextFieldbusinesslocation.setForeground(new java.awt.Color(0, 51, 51));

        jButtonaddbusiness.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jButtonaddbusiness.setForeground(new java.awt.Color(0, 51, 51));
        jButtonaddbusiness.setText("Add Business");
        jButtonaddbusiness.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonaddbusinessActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(25, 56, 82));
        jLabel6.setText("BUSINESS OWNER ADD BUSINESS PANEL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonshops, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(117, 117, 117)
                                .addComponent(jButtonrestaurants, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelbusinessname)
                            .addComponent(jLabelbusinesslocation))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonaddbusiness)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextFieldbusinessname, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldbusinesslocation, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonsetlocation))))
                .addContainerGap(478, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel6)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonshops, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonrestaurants, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelbusinessname)
                    .addComponent(jTextFieldbusinessname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelbusinesslocation)
                    .addComponent(jTextFieldbusinesslocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(jButtonsetlocation)
                .addGap(49, 49, 49)
                .addComponent(jButtonaddbusiness)
                .addContainerGap(329, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonshopsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonshopsActionPerformed
        // TODO add your handling code here:
        type = "Shop";
    }//GEN-LAST:event_jButtonshopsActionPerformed

    private void jButtonrestaurantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonrestaurantsActionPerformed
        // TODO add your handling code here:
        type = "Restaurant";
    }//GEN-LAST:event_jButtonrestaurantsActionPerformed

    private void jButtonsetlocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsetlocationActionPerformed
        // TODO add your handling code here:
        //Map
       // location = new String[] {"41", "-71"};
        location = jTextFieldbusinesslocation.getText().split(",", -2);
        JOptionPane.showMessageDialog(this, "Location set");
    }//GEN-LAST:event_jButtonsetlocationActionPerformed

    private void jButtonaddbusinessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonaddbusinessActionPerformed
        // TODO add your handling code here:
        if(type.equals("Shop")){
            Shop shop = business.getShopDirectory().createShop(jTextFieldbusinessname.getText(), location, userAccount.getUsername());
        }
        else if(type.equals("Restaurant")){
            Restaurant restaurant = business.getRestaurantDirectory().createRestaurant(jTextFieldbusinessname.getText(), location, userAccount.getUsername());
        }
        else{
            JOptionPane.showMessageDialog(this, "Please select either shop or restaurant type.");
            return;
        }
        JOptionPane.showMessageDialog(this, "Business added");
    }//GEN-LAST:event_jButtonaddbusinessActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonaddbusiness;
    private javax.swing.JButton jButtonrestaurants;
    private javax.swing.JButton jButtonsetlocation;
    private javax.swing.JButton jButtonshops;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelbusinesslocation;
    private javax.swing.JLabel jLabelbusinessname;
    private javax.swing.JTextField jTextFieldbusinesslocation;
    private javax.swing.JTextField jTextFieldbusinessname;
    // End of variables declaration//GEN-END:variables

}
