/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.BusinessOwnerRole;

import Project.SmartCity.Establishment.Restaurant;
import Project.SmartCity.Establishment.RestaurantDirectory;
import Project.SmartCity.Establishment.Shop;
import Project.SmartCity.Establishment.ShopDirectory;
import Project.SmartCity.SmartCity;
import Project.UserAccount.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author harooniqbal
 */
public class BusinessOwnerRemoveBusinessPanel extends javax.swing.JPanel {

    /**
     * Creates new form BusinessOwnerRemoveBusinessPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private SmartCity business;
    
    String type = "";
    
    public BusinessOwnerRemoveBusinessPanel(JPanel userProcessContainer, UserAccount account, SmartCity business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonshops = new javax.swing.JButton();
        jButtonrestaurants = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablebusownerremovebusiness = new javax.swing.JTable();
        jButtonremovebusiness = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(251, 211, 245));

        jButtonshops.setIcon(new javax.swing.ImageIcon("/Users/harooniqbal/Desktop/AEDProjectImages/shopitemsicon.png")); // NOI18N
        jButtonshops.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonshopsActionPerformed(evt);
            }
        });

        jButtonrestaurants.setIcon(new javax.swing.ImageIcon("/Users/harooniqbal/Desktop/AEDProjectImages/restbtn.png")); // NOI18N
        jButtonrestaurants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonrestaurantsActionPerformed(evt);
            }
        });

        jTablebusownerremovebusiness.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Location", "Revenue"
            }
        ));
        jScrollPane1.setViewportView(jTablebusownerremovebusiness);

        jButtonremovebusiness.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jButtonremovebusiness.setForeground(new java.awt.Color(0, 51, 51));
        jButtonremovebusiness.setText("Remove Business");
        jButtonremovebusiness.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonremovebusinessActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(25, 56, 82));
        jLabel6.setText("BUSINESS OWNER REMOVE BUSINESS PANEL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonshops, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonrestaurants, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54))
                            .addComponent(jLabel6)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addComponent(jButtonremovebusiness)))
                .addContainerGap(268, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel6)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonrestaurants, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonshops, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButtonremovebusiness)
                .addContainerGap(252, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonshopsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonshopsActionPerformed
        // TODO add your handling code here:
        type = "Shop";
        populateTable();
    }//GEN-LAST:event_jButtonshopsActionPerformed

    private void jButtonrestaurantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonrestaurantsActionPerformed
        // TODO add your handling code here:
        type = "Restaurant";
        populateTable();
    }//GEN-LAST:event_jButtonrestaurantsActionPerformed

    private void jButtonremovebusinessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonremovebusinessActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = jTablebusownerremovebusiness.getSelectedRow();
        
        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a row to be deleted.");
            return;
        }
        
        DefaultTableModel records = (DefaultTableModel) jTablebusownerremovebusiness.getModel();
        String name = (String) records.getValueAt(selectedRowIndex, 1);
        if(type.equals("Shop")){
            Shop shop = business.getShopDirectory().getShop(name);
            business.getShopDirectory().shopList.remove(shop);
            populateTable();
        }
        else if(type.equals("Restaurant")){
            Restaurant restaurant = business.getRestaurantDirectory().getRestaurant(name);
            business.getRestaurantDirectory().restaurantList.remove(restaurant);
            populateTable();
        }
        else{
            JOptionPane.showMessageDialog(this, "Please select either a shop or a restaurant.");
            return;
        }
        JOptionPane.showMessageDialog(this, "Business removed");
    }//GEN-LAST:event_jButtonremovebusinessActionPerformed
    
    private void populateTable() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        DefaultTableModel records = (DefaultTableModel) jTablebusownerremovebusiness.getModel();
        
        if(type.equals("Shop")){
            ShopDirectory shopDirectory = business.getShopDirectory();
            records.setRowCount(0); //Clear empty records

            for(Shop o : shopDirectory.getShopList()){
                if(o.getUsername().equals(userAccount.getUsername())){
                    Object[] row = new Object[4];
                    row[0] = o.getId();
                    //row[0] = vs.getDate();
                    row[1] = o.getName();
                    row[2] = o.getLocation()[0]+"/"+o.getLocation()[1];
                    row[3] = o.getRevenue();

                    records.addRow(row);
                }
            }
        }
        else if(type.equals("Restaurant")){
            RestaurantDirectory restaurantDirectory = business.getRestaurantDirectory();
            records.setRowCount(0); //Clear empty records

            for(Restaurant o : restaurantDirectory.getRestaurantList()){
                if(o.getUsername().equals(userAccount.getUsername())){
                    Object[] row = new Object[4];
                    row[0] = o.getId();
                    //row[0] = vs.getDate();
                    row[1] = o.getName();
                    row[2] = o.getLocation()[0]+"/"+o.getLocation()[1];
                    row[3] = o.getRevenue();

                    records.addRow(row);
                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonremovebusiness;
    private javax.swing.JButton jButtonrestaurants;
    private javax.swing.JButton jButtonshops;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablebusownerremovebusiness;
    // End of variables declaration//GEN-END:variables
}
