/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.TourGuideRole;

import Project.SmartCity.SmartCity;
import Project.SmartCity.TourismSystem.Aquarium;
import Project.SmartCity.TourismSystem.Beach;
import Project.SmartCity.TourismSystem.Garden;
import Project.SmartCity.TourismSystem.Museum;
import Project.UserAccount.UserAccount;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author harooniqbal
 */
public class TourGuideSetTouristSpotPanel extends javax.swing.JPanel {

    /**
     * Creates new form TourGuideSetTouristSpotPanel
     */
    
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private SmartCity business;
    String[] location = {"41","-71"};
    
    String type="",picPath = "";
    public TourGuideSetTouristSpotPanel(JPanel userProcessContainer, UserAccount account, SmartCity business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonbeach = new javax.swing.JButton();
        jButtonmuseum = new javax.swing.JButton();
        jButtongarden = new javax.swing.JButton();
        jButtonaquarium = new javax.swing.JButton();
        jButtonshowlocation = new javax.swing.JButton();
        nametxt = new javax.swing.JTextField();
        costtxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonaddpics = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jButtonaddspot = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        costtxt1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(194, 216, 220));

        jButtonbeach.setIcon(new javax.swing.ImageIcon("/Users/harooniqbal/Desktop/AEDProjectImages/beach1.png")); // NOI18N
        jButtonbeach.setText("Beaches");
        jButtonbeach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonbeachActionPerformed(evt);
            }
        });

        jButtonmuseum.setIcon(new javax.swing.ImageIcon("/Users/harooniqbal/Desktop/AEDProjectImages/museum1.png")); // NOI18N
        jButtonmuseum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonmuseumActionPerformed(evt);
            }
        });

        jButtongarden.setIcon(new javax.swing.ImageIcon("/Users/harooniqbal/Desktop/AEDProjectImages/garden1.png")); // NOI18N
        jButtongarden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtongardenActionPerformed(evt);
            }
        });

        jButtonaquarium.setIcon(new javax.swing.ImageIcon("/Users/harooniqbal/Desktop/AEDProjectImages/aquarium1.png")); // NOI18N
        jButtonaquarium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonaquariumActionPerformed(evt);
            }
        });

        jButtonshowlocation.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jButtonshowlocation.setForeground(new java.awt.Color(0, 51, 51));
        jButtonshowlocation.setText("Set Location");
        jButtonshowlocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonshowlocationActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("Name:");

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("Cost:");

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(25, 56, 82));
        jLabel6.setText("TOUR GUIDE SET TOURIST SPOT");

        jButtonaddpics.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jButtonaddpics.setForeground(new java.awt.Color(0, 51, 51));
        jButtonaddpics.setText("Add Pictures");
        jButtonaddpics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonaddpicsActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon("/Users/harooniqbal/Desktop/AEDProjectImages/tourguideicon2.png")); // NOI18N
        jLabel11.setText("jLabel10");

        jButtonaddspot.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jButtonaddspot.setForeground(new java.awt.Color(0, 51, 51));
        jButtonaddspot.setText("Add Tourist Spot");
        jButtonaddspot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonaddspotActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon("/Users/harooniqbal/Desktop/AEDProjectImages/tourguidesetspot.png")); // NOI18N

        costtxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costtxt1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 51));
        jLabel4.setText("Location:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonshowlocation)
                .addGap(261, 261, 261)
                .addComponent(jButtonaddpics)
                .addGap(416, 416, 416))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(273, 273, 273)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jButtonbeach, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(173, 173, 173)
                                .addComponent(jButtonaddspot))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonmuseum, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(jButtongarden, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(jButtonaquarium, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2))
                                        .addGap(68, 68, 68)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(nametxt)
                                            .addComponent(costtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(46, 46, 46)
                                        .addComponent(costtxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(675, 675, 675)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel6))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonmuseum, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonaquarium, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtongarden, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonbeach, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(costtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(costtxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonshowlocation)
                    .addComponent(jButtonaddpics))
                .addGap(20, 20, 20)
                .addComponent(jButtonaddspot)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonbeachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonbeachActionPerformed
        // TODO add your handling code here:
        type = "Beach";
        JOptionPane.showMessageDialog(this, "Beach Option Selected");
            
    }//GEN-LAST:event_jButtonbeachActionPerformed

    private void jButtonmuseumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonmuseumActionPerformed
        // TODO add your handling code here:
        type = "Museum";
        JOptionPane.showMessageDialog(this, "Museum Option Selected");
            
    }//GEN-LAST:event_jButtonmuseumActionPerformed

    private void jButtongardenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtongardenActionPerformed
        // TODO add your handling code here:
        type = "Garden";
        JOptionPane.showMessageDialog(this, "Garden Option Selected");
            
    }//GEN-LAST:event_jButtongardenActionPerformed

    private void jButtonaquariumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonaquariumActionPerformed
        // TODO add your handling code here:
        type = "Aquarium";
        JOptionPane.showMessageDialog(this, "Aquarium Option Selected");
            
    }//GEN-LAST:event_jButtonaquariumActionPerformed

    private void jButtonshowlocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonshowlocationActionPerformed
        // TODO add your handling code here:
        location = costtxt1.getText().split(",", -2);
        
        JOptionPane.showMessageDialog(this, "Location Set.");
        
    }//GEN-LAST:event_jButtonshowlocationActionPerformed

    private void jButtonaddpicsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonaddpicsActionPerformed
        // TODO add your handling code here:
        JFileChooser picture = new JFileChooser();
        //Image extension filter
        FileNameExtensionFilter filter = new FileNameExtensionFilter("IMAGES", "png", "jpg", "jpeg");
        picture.addChoosableFileFilter(filter);
        int showOpenDialog = picture.showOpenDialog(null);
        if (showOpenDialog == JFileChooser.APPROVE_OPTION) {
            File pic = picture.getSelectedFile();
            picPath = pic.getAbsolutePath();
            //    personal.setPicPath(path);
            //Corresponding display code:
            //        ImageIcon tmp = new ImageIcon(personal.getPicPath());
            //        Image img = tmp.getImage().getScaledInstance(230, 155, Image.SCALE_SMOOTH);
            //        JLabel imgLabel = new JLabel(new ImageIcon(img));
            //        imgLabel.setSize(230, 155);
            //        imgPanel.add(imgLabel);
        }
        JOptionPane.showMessageDialog(this, "Picture Added.");
        
    }//GEN-LAST:event_jButtonaddpicsActionPerformed

    private void jButtonaddspotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonaddspotActionPerformed
        // TODO add your handling code here:
        //String[] location = {"41","-71"};
        switch(type){
            case "Beach":
                Beach beach = business.getBeachDirectory().createBeach(nametxt.getText(), location, userAccount.getUsername());
                beach.setpicPath(picPath);
                beach.setCost(costtxt.getText());
                break;
            case "Museum":
                Museum museum = business.getMuseumDirectory().createMuseum(nametxt.getText(), location, userAccount.getUsername());
                museum.setCost(costtxt.getText());
                museum.setpicPath(picPath);
                break;
            case "Garden":
                Garden garden = business.getGardenDirectory().createGarden(nametxt.getText(), location, userAccount.getUsername());
                garden.setCost(costtxt.getText());
                garden.setpicPath(picPath);
                
                break;
            case "Aquarium":
                Aquarium aquarium = business.getAquariumDirectory().createAquarium(nametxt.getText(), location, userAccount.getUsername());
                aquarium.setCost(costtxt.getText());
                aquarium.setpicPath(picPath);
                break;
            default:
                JOptionPane.showMessageDialog(this, "Please select either a beach, museum, garden or an aquarium.");
                return;
        }
        JOptionPane.showMessageDialog(this, "Tourist Spot Added.");
        
    }//GEN-LAST:event_jButtonaddspotActionPerformed

    private void costtxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costtxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_costtxt1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField costtxt;
    private javax.swing.JTextField costtxt1;
    private javax.swing.JButton jButtonaddpics;
    private javax.swing.JButton jButtonaddspot;
    private javax.swing.JButton jButtonaquarium;
    private javax.swing.JButton jButtonbeach;
    private javax.swing.JButton jButtongarden;
    private javax.swing.JButton jButtonmuseum;
    private javax.swing.JButton jButtonshowlocation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nametxt;
    // End of variables declaration//GEN-END:variables
}
