/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

//import com.teamdev.jxbrowser.browser.Browser;
//import com.teamdev.jxbrowser.engine.Engine;
//import com.teamdev.jxbrowser.engine.EngineOptions;
//import static com.teamdev.jxbrowser.engine.RenderingMode.HARDWARE_ACCELERATED;
//import com.teamdev.jxbrowser.view.swing.BrowserView;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.URL;
 
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author Okami
 */
public class MapsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MapsJPanel
     */
    
//    JPanel userProcessContainer;
//    Browser browser;
    
//    public MapsJPanel(JPanel userProcessContainer) {
//        initComponents();
//        this.userProcessContainer = userProcessContainer;
//        
//        Engine engine = Engine.newInstance(
//        EngineOptions.newBuilder(HARDWARE_ACCELERATED)
//                .licenseKey("1BNDHFSC1FYUHC2YD54FHY898RKOF62AOQFQV3KU2RVVNFWSNL1LYMT5PNJLBQOB43WCCI")
//                .build());
//        System.setProperty("jxbrowser.license.key", "1BNDHFSC1FYUHC2YD54FHY898RKOF62AOQFQV3KU2RVVNFWSNL1LYMT5PNJLBQOB43WCCI");
//        //BrowserUtil;
//        browser = engine.newBrowser();
//        BrowserView view = BrowserView.newInstance(browser);
//        browser.navigation().loadUrl("https://www.google.com/maps");
//        
//        jPanel2.add(view, "a");
//    }

    public MapsJPanel() {
        JFrame test = new JFrame("Google Maps");
 
        try {
            String latitude = "40.714728";
            String longitude = "-73.998672";
 
            String imageUrl = "https://maps.googleapis.com/maps/api/staticmap?center="
                    + latitude
                    + ","
                    + longitude
                    + "&zoom=11&size=612x612&scale=2&maptype=roadmap";
            String destinationFile = "image.jpg";
            System.out.println(imageUrl);
            // read the map image from Google
            // then save it to a local file: image.jpg
            //
            URL url = new URL(imageUrl);
            InputStream is = url.openStream();
            OutputStream os = new FileOutputStream(destinationFile);
 
            byte[] b = new byte[2048];
            int length;
 
            while ((length = is.read(b)) != -1) {
                os.write(b, 0, length);
            }
 
            is.close();
            os.close();
        } catch (IOException e) {
            e.printStackTrace();
            System.exit(1);
        }
 
        // create a GUI component that loads the image: image.jpg
        //
        ImageIcon imageIcon = new ImageIcon((new ImageIcon("image.jpg"))
                .getImage().getScaledInstance(630, 600,
                        java.awt.Image.SCALE_SMOOTH));
        test.add(new JLabel(imageIcon));
 
        // show the GUI window
        test.setVisible(true);
        test.pack();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mapSplitPane = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        setLocationbtn = new javax.swing.JButton();
        retrieveLocationbtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        mapSplitPane.setDividerLocation(80);
        mapSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        setLocationbtn.setText("Set Location");
        setLocationbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setLocationbtnActionPerformed(evt);
            }
        });

        retrieveLocationbtn.setText("Retrieve Location");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(setLocationbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 231, Short.MAX_VALUE)
                .addComponent(retrieveLocationbtn)
                .addGap(237, 237, 237))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(setLocationbtn)
                    .addComponent(retrieveLocationbtn))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        mapSplitPane.setTopComponent(jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 942, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 515, Short.MAX_VALUE)
        );

        mapSplitPane.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mapSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 944, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mapSplitPane)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void setLocationbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setLocationbtnActionPerformed
        // TODO add your handling code here:
//        try {
//            double lat = 0;
//            double lon = 0;
//            if (browser.url()!= null) {
//
//                System.out.println(browser.url());
//                String[] a = browser.url().split("!3d", 0);
//                String[] b = a[1].split("!4d");
//                System.out.println("Lat" + b[0] + "  " + "Lon" + b[1]);
//                lat = Double.parseDouble(b[0]);
//                lon = Double.parseDouble(b[1]);
//            }
//            System.out.println("Lat"+lat);
//            System.out.println("Lon"+lon);
//            userProcessContainer.remove(this);
//            
//
//            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
//            layout.previous(userProcessContainer);
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, "Set Position first");
//        }
    }//GEN-LAST:event_setLocationbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane mapSplitPane;
    private javax.swing.JButton retrieveLocationbtn;
    private javax.swing.JButton setLocationbtn;
    // End of variables declaration//GEN-END:variables
}
