/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import javax.mail.*;
import javax.mail.internet.*;
import javax.activation.*;
import Project.Employee.Employee;
import Project.Person.Person;
import Project.Role.AdminRole;
import Project.Role.BusinessOwnerRole;
import Project.Role.CommuterRole;
import Project.Role.CustomerRole;
import Project.Role.DeliverManRole;
import Project.Role.DoctorRole;
import Project.Role.FacultyRole;
import Project.Role.ManagerRole;
import Project.Role.PatientRole;
import Project.Role.PharmacistRole;
import Project.Role.StudentRole;
import Project.Role.TourGuideRole;
import Project.Role.TouristRole;
import Project.SmartCity.EstablishmentRoles.BusinessOwner;
import Project.SmartCity.SmartCity;
import Project.UserAccount.UserAccount;
import java.io.File;
import java.util.Properties;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Okami
 */
public class SignUpJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SignUpJPanel
     */
    private SmartCity system;
    String picPath;
    
    public SignUpJPanel(SmartCity system) {
        initComponents();
        this.system = system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        phonetxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        emailtxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        addresstxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        usernametxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        roleList = new javax.swing.JList<>();
        lblPicture = new javax.swing.JLabel();
        btnBrowse = new javax.swing.JButton();
        submitbtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        passwordtxt = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(181, 241, 202));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("Name:");

        nametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nametxtActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("Phone Number:");

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("Email:");

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 51));
        jLabel4.setText("Address:");

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 51));
        jLabel5.setText("Username:");

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 51));
        jLabel6.setText("Password:");

        roleList.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        roleList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Business Owner", "Commuter", "Customer", "Doctor", "Faculty", "General User", "Manager", "Patient", "Pharmacist", "Restaurant Admin", "Shop Admin", "Student", "Tour Guide", "Tourist" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(roleList);

        lblPicture.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblPicture.setForeground(new java.awt.Color(0, 51, 51));
        lblPicture.setText("Upload Picture:");

        btnBrowse.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        btnBrowse.setForeground(new java.awt.Color(0, 51, 51));
        btnBrowse.setText("Browse");
        btnBrowse.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        submitbtn.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        submitbtn.setForeground(new java.awt.Color(0, 51, 51));
        submitbtn.setText("Submit");
        submitbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        submitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbtnActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 51));
        jLabel9.setText("Select Role:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(lblPicture))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(btnBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(phonetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addresstxt, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(usernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passwordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(submitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(342, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(phonetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailtxt))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addresstxt, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(usernametxt))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPicture)
                    .addComponent(btnBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(submitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(237, Short.MAX_VALUE))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 940, 900));

        jPanel1.setBackground(new java.awt.Color(129, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jLabel7.setIcon(new javax.swing.ImageIcon("/Users/harooniqbal/Desktop/AEDProjectImages/smartcitysmall.png")); // NOI18N
        jLabel7.setSize(new java.awt.Dimension(50, 50));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(129, 204, 204));
        jTextField2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(0, 51, 51));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("YOUR HOME.");
        jTextField2.setBorder(null);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(129, 204, 204));
        jTextField3.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(0, 51, 51));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("WELCOME TO YOUR CITY,");
        jTextField3.setBorder(null);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(206, Short.MAX_VALUE)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(197, 197, 197))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -2, 520, 900));
    }// </editor-fold>//GEN-END:initComponents

    private void nametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nametxtActionPerformed

    private void submitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbtnActionPerformed
        // TODO add your handling code here:
        String role;
        if(Pattern.matches("^(?=(.*[a-z]){1,})(?=(.*[\\d]){1,})(?=(.*[\\W]){1,})(?!.*\\s).{5,30}$", passwordtxt.getText())==false){
            JOptionPane.showMessageDialog(this, "Please provide correct format for password.");
            return;
        }
        role = roleList.getSelectedValue();
        Person p = system.getPersonDirectory().createPerson(nametxt.getText(), addresstxt.getText(), emailtxt.getText(), phonetxt.getText(), picPath);
        Employee employee = system.getEmployeeDirectory().createEmployee(role);
        UserAccount ua;
        switch(role) {
                case "Business Owner":
                    ua = system.getUserAccountDirectory().createUserAccount(usernametxt.getText(), passwordtxt.getText(), employee, new BusinessOwnerRole());
                    system.getBusinessOwnerDirectory().createBusinessOwner(usernametxt.getText());
                    break;
                case "Commuter":    
                    ua = system.getUserAccountDirectory().createUserAccount(usernametxt.getText(), passwordtxt.getText(), employee, new CommuterRole());
                    system.getCommuterDirectory().createCommuter(usernametxt.getText());
                    break;
                case "Customer":
                    ua = system.getUserAccountDirectory().createUserAccount(usernametxt.getText(), passwordtxt.getText(), employee, new CustomerRole());
                    break;
                case "Delivery": 
                    ua = system.getUserAccountDirectory().createUserAccount(usernametxt.getText(), passwordtxt.getText(), employee, new DeliverManRole());
                    break;
                case "Doctor":
                    ua = system.getUserAccountDirectory().createUserAccount(usernametxt.getText(), passwordtxt.getText(), employee, new DoctorRole());
                    system.getHospitalDirectory().getHospital("SmartCity Public Hospital").getDoctorDirectory().createDoctor(usernametxt.getText(), "Urologist", "SmartCity Public Hospital");
                    break;
                case "Faculty": 
                    ua = system.getUserAccountDirectory().createUserAccount(usernametxt.getText(), passwordtxt.getText(), employee, new FacultyRole());
                    break;
                case "General User":
                    ua = system.getUserAccountDirectory().createUserAccount(usernametxt.getText(), passwordtxt.getText(), employee, new AdminRole());
                    break;
                case "Manager": 
                    ua = system.getUserAccountDirectory().createUserAccount(usernametxt.getText(), passwordtxt.getText(), employee, new ManagerRole());
                    break;
                case "Patient":
                    ua = system.getUserAccountDirectory().createUserAccount(usernametxt.getText(), passwordtxt.getText(), employee, new PatientRole());
                    system.getPatientDirectory().createPatient(usernametxt.getText(), "23 years", "Diabetic");
                    break;
                case "Pharmacist": 
                    ua = system.getUserAccountDirectory().createUserAccount(usernametxt.getText(), passwordtxt.getText(), employee, new PharmacistRole());
                    system.getPharmacyDirectory().getPharmacy("SmartCity Pharmacy").getPharmacistDirectory().createPharmacist(usernametxt.getText(), "SmartCity Pharmacy", "SmartCity Street 1");
                    break;
                case "Restaurant Admin":
                    ua = system.getUserAccountDirectory().createUserAccount(usernametxt.getText(), passwordtxt.getText(), employee, new AdminRole());
                    break;
                case "Student":
                    ua = system.getUserAccountDirectory().createUserAccount(usernametxt.getText(), passwordtxt.getText(), employee, new StudentRole());
                    break;
                case "Tour Guide":
                    ua = system.getUserAccountDirectory().createUserAccount(usernametxt.getText(), passwordtxt.getText(), employee, new TourGuideRole());
                    system.getTouristDirectory().createTourist(usernametxt.getText(), "Highly Experienced", "SmartCity ManagementSystem");
                    break;
                case "Tourist": 
                    ua = system.getUserAccountDirectory().createUserAccount(usernametxt.getText(), passwordtxt.getText(), employee, new TouristRole());
                    system.getTouristDirectory().createTourist(usernametxt.getText(), "United States", "SmartCity ManagementSystem");
                    break;
                default:
                    JOptionPane.showMessageDialog(this, "Select an appropriate role.");
                    return;
        }
//            UserAccount ua = system.getUserAccountDirectory().createUserAccount(usernametxt.getText(), passwordtxt.getText(), employee, new CustomerRole());
        
        sendEmail(emailtxt.getText(), nametxt.getText());
        sendSms(phonetxt.getText(), nametxt.getText());
        
        nametxt.setText("");
        emailtxt.setText("");
        phonetxt.setText("");
        addresstxt.setText("");
        usernametxt.setText("");
        passwordtxt.setText("");
    }//GEN-LAST:event_submitbtnActionPerformed

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        // TODO add your handling code here:
        JFileChooser picture = new JFileChooser();
        //Image extension filter
        FileNameExtensionFilter filter = new FileNameExtensionFilter("IMAGES", "png", "jpg", "jpeg");
        picture.addChoosableFileFilter(filter);
        int showOpenDialog = picture.showOpenDialog(null);
        if (showOpenDialog == JFileChooser.APPROVE_OPTION) {
            File pic = picture.getSelectedFile();
            picPath = pic.getAbsolutePath();
        //    personal.setPicPath(path);
        
        //Corresponding display code:
//        ImageIcon tmp = new ImageIcon(personal.getPicPath());
//        Image img = tmp.getImage().getScaledInstance(230, 155, Image.SCALE_SMOOTH);
//        JLabel imgLabel = new JLabel(new ImageIcon(img));
//        imgLabel.setSize(230, 155);
//        imgPanel.add(imgLabel);
        }
    }//GEN-LAST:event_btnBrowseActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void sendEmail(String text, String name) {
        final String username = "smartcitymanagementsystem@gmail.com";
        final String password = "Password@123";

        Properties props = new Properties();
        props.put("mail.smtp.starttls.enable", "true");
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.host", "smtp.gmail.com");
        props.put("mail.smtp.port", "587");

        Session session = Session.getInstance(props,
          new javax.mail.Authenticator() {
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(username, password);
            }
          });

        try {

            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress("smartcitymanagementsystem@gmail.com"));
            message.setRecipients(Message.RecipientType.TO,
                InternetAddress.parse(text));
            message.setSubject("Welcome to SmartCity Management System");
            message.setText("Dear "+name+","
                + "\n\n Congratulations! You are now a registered member of the SmartCity Community! Live long and prosper.");

            Transport.send(message);

            JOptionPane.showMessageDialog(this, "Successfully Registered!");

        } catch (MessagingException e) {
            throw new RuntimeException(e);
        } 
    } 
    
    private void sendSms(String phone, String name) {
        //Code SMS here:
    } 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addresstxt;
    private javax.swing.JButton btnBrowse;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lblPicture;
    private javax.swing.JTextField nametxt;
    private javax.swing.JPasswordField passwordtxt;
    private javax.swing.JTextField phonetxt;
    private javax.swing.JList<String> roleList;
    private javax.swing.JButton submitbtn;
    private javax.swing.JTextField usernametxt;
    // End of variables declaration//GEN-END:variables
}
